import type { AssessmentQuestion } from '@/types';

export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'a1',
    type: 'multiple_choice',
    question: 'What happens when a Python interpreter executes a script line by line?',
    options: [
      'It converts the entire file to machine code first, then runs it',
      'It reads each line, parses it, and executes it immediately before moving to the next',
      'It sends each line to the operating system for execution',
      'It compiles each function separately and caches the results',
    ],
    correctAnswer: 'It reads each line, parses it, and executes it immediately before moving to the next',
    explanation: 'Python is an interpreted language. The interpreter processes code sequentially at runtime, unlike compiled languages that translate the entire program first.',
    topic: 'programming_fundamentals',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'a2',
    type: 'predict_output',
    question: 'What will this Python code print?',
    code: `x = 10\ny = x\nx = 20\nprint(y)`,
    language: 'python',
    correctAnswer: '10',
    explanation: 'When y = x executes, y gets a copy of x\'s value (10). Changing x to 20 does not affect y because integers are immutable in Python.',
    topic: 'python',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'a3',
    type: 'explain_code',
    question: 'In one sentence, explain what this function does:',
    code: `def validate_stock(qty_available, qty_requested):\n    if qty_requested <= 0:\n        return False, "Quantity must be positive"\n    if qty_requested > qty_available:\n        return False, "Insufficient stock"\n    return True, "OK"`,
    language: 'python',
    correctAnswer: 'validates that requested quantity is positive and does not exceed available stock',
    explanation: 'The function checks two business rules: quantity must be positive, and requested amount cannot exceed available stock. It returns a tuple of (success boolean, message).',
    topic: 'python',
    difficulty: 'medium',
    points: 8,
  },
  {
    id: 'a4',
    type: 'multiple_choice',
    question: 'In Object-Oriented Programming, what is the primary purpose of a class?',
    options: [
      'To store global variables accessible from anywhere',
      'To define a blueprint that combines data (attributes) and behavior (methods) for creating objects',
      'To replace the need for functions entirely',
      'To compile code faster',
    ],
    correctAnswer: 'To define a blueprint that combines data (attributes) and behavior (methods) for creating objects',
    explanation: 'A class is a template. Objects (instances) are created from it, each with their own attribute values but sharing the same method definitions.',
    topic: 'programming_fundamentals',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'a5',
    type: 'write_query',
    question: 'Write a SQL query to find all sales orders where the total amount exceeds 1000. Table: sales_orders (id, client_id, total_amount, status, order_date)',
    correctAnswer: 'SELECT * FROM sales_orders WHERE total_amount > 1000',
    explanation: 'A simple SELECT with WHERE filter on total_amount. In production, you would also specify needed columns instead of SELECT *.',
    topic: 'sql',
    difficulty: 'easy',
    points: 8,
  },
  {
    id: 'a6',
    type: 'multiple_choice',
    question: 'What is a Foreign Key in a relational database?',
    options: [
      'A key that encrypts sensitive data',
      'A column that references the primary key of another table, establishing a relationship',
      'A unique index on every table',
      'A backup copy of the primary key',
    ],
    correctAnswer: 'A column that references the primary key of another table, establishing a relationship',
    explanation: 'Foreign keys enforce referential integrity. For example, sales_order.client_id references clients.id.',
    topic: 'sql',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'a7',
    type: 'find_error',
    question: 'Find the error in this JavaScript code:',
    code: `const orders = [{id: 1, total: 500}, {id: 2, total: 800}];\nconst highValue = orders.filter(o => o.total > 600);\nconsole.log(highValue.length);\nhighValue.push({id: 3, total: 1200});\nconsole.log(orders.length);`,
    language: 'javascript',
    options: [
      'filter is not a valid array method',
      'There is no error — this code works correctly',
      'push cannot be used on filtered arrays',
      'The comparison operator should be >=',
    ],
    correctAnswer: 'There is no error — this code works correctly',
    explanation: 'filter returns a new array. highValue has 1 element (order 2). Pushing to highValue does not affect the original orders array. Output: 1, then 2.',
    topic: 'javascript',
    difficulty: 'medium',
    points: 8,
  },
  {
    id: 'a8',
    type: 'multiple_choice',
    question: 'In HTML, what is the purpose of semantic elements like <header>, <nav>, and <main>?',
    options: [
      'They make the page load faster',
      'They describe the meaning/purpose of content, improving accessibility and SEO',
      'They are required for CSS to work',
      'They replace the need for JavaScript',
    ],
    correctAnswer: 'They describe the meaning/purpose of content, improving accessibility and SEO',
    explanation: 'Semantic HTML tells browsers, screen readers, and developers what each section represents.',
    topic: 'html_css',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'a9',
    type: 'explain_code',
    question: 'What does this XML define in an Odoo context?',
    code: `<record id="view_sale_order_form" model="ir.ui.view">\n  <field name="name">sale.order.form</field>\n  <field name="model">sale.order</field>\n  <field name="arch" type="xml">\n    <form>\n      <field name="partner_id"/>\n      <field name="amount_total"/>\n    </form>\n  </field>\n</record>`,
    language: 'xml',
    correctAnswer: 'a form view for the sale.order model showing partner and total amount fields',
    explanation: 'This Odoo XML record defines a form view (ir.ui.view) for the sale.order model with two visible fields.',
    topic: 'xml',
    difficulty: 'medium',
    points: 8,
  },
  {
    id: 'a10',
    type: 'multiple_choice',
    question: 'What HTTP method should be used to retrieve data without modifying it?',
    options: ['POST', 'PUT', 'GET', 'DELETE'],
    correctAnswer: 'GET',
    explanation: 'GET is idempotent and safe — it retrieves resources without side effects. POST creates, PUT updates, DELETE removes.',
    topic: 'api',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'a11',
    type: 'multiple_choice',
    question: 'What is the primary purpose of Git?',
    options: [
      'To compile code',
      'To track changes in source code and enable collaboration through version history',
      'To deploy applications to production',
      'To run automated tests',
    ],
    correctAnswer: 'To track changes in source code and enable collaboration through version history',
    explanation: 'Git is a distributed version control system. It records every change, enables branching, and supports team collaboration.',
    topic: 'git',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'a12',
    type: 'identify_architecture',
    question: 'In a layered architecture (Controller → Service → Repository → Database), where should business validation logic like "order total must be positive" live?',
    options: [
      'In the Controller — it receives the request first',
      'In the Service layer — it handles business rules and orchestration',
      'In the Database — as a constraint only',
      'In the frontend only',
    ],
    correctAnswer: 'In the Service layer — it handles business rules and orchestration',
    explanation: 'Business logic belongs in the Service layer. Controllers handle HTTP, Repositories handle data access, and the database enforces constraints as a safety net.',
    topic: 'architecture',
    difficulty: 'medium',
    points: 8,
  },
  {
    id: 'a13',
    type: 'multiple_choice',
    question: 'In Odoo, what does models.Model represent?',
    options: [
      'A database table definition with ORM capabilities',
      'A CSS stylesheet',
      'An API endpoint',
      'A JavaScript component',
    ],
    correctAnswer: 'A database table definition with ORM capabilities',
    explanation: 'Odoo models inherit from models.Model. Each model maps to a database table and provides ORM methods (create, write, search, etc.).',
    topic: 'odoo',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'a14',
    type: 'analyze_erp',
    question: 'A user reports: "I cannot confirm this sales order." As an ERP technical specialist, what is your FIRST investigation step?',
    options: [
      'Delete the sales order and recreate it',
      'Check the order state, user permissions, and any validation/constraints blocking confirmation',
      'Restart the Odoo server',
      'Modify the database directly with UPDATE',
    ],
    correctAnswer: 'Check the order state, user permissions, and any validation/constraints blocking confirmation',
    explanation: 'Professional ERP investigation starts with understanding the current state: order status, user roles, record rules, and validation methods — never with destructive actions.',
    topic: 'erp_analysis',
    difficulty: 'medium',
    points: 8,
  },
  {
    id: 'a15',
    type: 'find_error',
    question: 'This Python function has a bug. What type of error will occur?',
    code: `def calculate_line_total(quantity, unit_price):\n    return quantity * unit_price\n\ntotal = calculate_line_total("5", 100)\nprint(total + 50)`,
    language: 'python',
    correctAnswer: 'TypeError',
    explanation: 'Multiplying string "5" by 100 gives "5" repeated 100 times (string repetition). Then "5..." + 50 fails because you cannot concatenate str and int.',
    topic: 'debugging',
    difficulty: 'medium',
    points: 8,
  },
  {
    id: 'a16',
    type: 'explain_code',
    question: 'What does this Odoo ORM code do?',
    code: `orders = self.env['sale.order'].search([\n    ('state', '=', 'draft'),\n    ('partner_id', '=', client_id)\n], limit=10)`,
    language: 'python',
    correctAnswer: 'searches for up to 10 draft sales orders for a specific client',
    explanation: 'search() queries the sale.order model with domain filters: state is draft AND partner matches client_id, returning max 10 records.',
    topic: 'code_reading',
    difficulty: 'medium',
    points: 8,
  },
  {
    id: 'a17',
    type: 'multiple_choice',
    question: 'Before running UPDATE on a production ERP database, what must you ALWAYS do first?',
    options: [
      'Run DELETE to clean old data',
      'Run a SELECT with the same WHERE clause to verify which rows will be affected',
      'Disable all user access permanently',
      'Skip staging and apply directly',
    ],
    correctAnswer: 'Run a SELECT with the same WHERE clause to verify which rows will be affected',
    explanation: 'SELECT before UPDATE is the golden rule of production database safety. Always verify affected rows and counts before any modification.',
    topic: 'production_safety',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'a18',
    type: 'write_code',
    question: 'Write a Python function that returns True if a number is even, False otherwise. Function name: is_even',
    correctAnswer: 'def is_even(n): return n % 2 == 0',
    explanation: 'The modulo operator (%) returns the remainder. If n % 2 == 0, the number is evenly divisible by 2.',
    topic: 'python',
    difficulty: 'easy',
    points: 8,
  },
  {
    id: 'a19',
    type: 'multiple_choice',
    question: 'Which professional explanation best describes a bug where a button click does nothing?',
    options: [
      'The button is broken',
      'The database has a problem',
      'The frontend event handler fires but the API call returns HTTP 500 due to an unhandled exception in the service layer before the database transaction begins',
      'Odoo is slow today',
    ],
    correctAnswer: 'The frontend event handler fires but the API call returns HTTP 500 due to an unhandled exception in the service layer before the database transaction begins',
    explanation: 'Professional technical communication identifies the layer, the evidence (HTTP 500), and the failure point (service layer, before DB transaction).',
    topic: 'technical_communication',
    difficulty: 'medium',
    points: 8,
  },
  {
    id: 'a20',
    type: 'predict_output',
    question: 'What SQL result count would you expect from this query if there are 3 clients and 5 orders (some clients have multiple orders)?',
    code: `SELECT c.name, COUNT(o.id) as order_count\nFROM clients c\nLEFT JOIN sales_orders o ON o.client_id = c.id\nGROUP BY c.name;`,
    language: 'sql',
    correctAnswer: '3',
    explanation: 'GROUP BY c.name produces one row per client. LEFT JOIN ensures all 3 clients appear even if they have zero orders.',
    topic: 'sql',
    difficulty: 'hard',
    points: 8,
  },
];
