import type { LanguageComparison } from '@/types';

export const COMPARISONS: LanguageComparison[] = [
  {
    concept: 'Variable',
    python: { code: 'customer_name = "Acme Corp"\nquantity = 10\nprice = 99.50\nis_active = True', notes: 'Dynamic typing. No declaration needed. snake_case convention.' },
    csharp: { code: 'string customerName = "Acme Corp";\nint quantity = 10;\ndecimal price = 99.50m;\nbool isActive = true;', notes: 'Static typing. Type declared explicitly. PascalCase for variables in some conventions.' },
    javascript: { code: 'const customerName = "Acme Corp";\nlet quantity = 10;\nconst price = 99.50;\nlet isActive = true;', notes: 'Dynamic typing. const for immutable binding, let for reassignable. camelCase convention.' },
    sameConcept: 'All three store named values in memory for later use.',
    syntaxDifference: 'Python: name = value. C#: Type name = value. JS: const/let name = value.',
    runtimeDifference: 'Python and JS determine types at runtime. C# checks types at compile time.',
    typeSystemDifference: 'Python/JS are dynamically typed. C# is statically typed with type inference (var).',
    typicalUseCase: 'Storing user input, configuration, calculation results.',
    erpUseCase: 'order_id, partner_name, amount_total, state — every ERP field is a typed variable.',
  },
  {
    concept: 'Condition',
    python: { code: 'if quantity > 0 and stock_available:\n    process_order()\nelif quantity == 0:\n    raise ValueError("Empty order")\nelse:\n    reject_order()', notes: 'Uses if/elif/else. Boolean operators: and, or, not. Colons and indentation.' },
    csharp: { code: 'if (quantity > 0 && stockAvailable)\n{\n    ProcessOrder();\n}\nelse if (quantity == 0)\n{\n    throw new ArgumentException("Empty order");\n}\nelse\n{\n    RejectOrder();\n}', notes: 'Curly braces for blocks. && for AND, || for OR. Semicolons required.' },
    javascript: { code: 'if (quantity > 0 && stockAvailable) {\n    processOrder();\n} else if (quantity === 0) {\n    throw new Error("Empty order");\n} else {\n    rejectOrder();\n}', notes: 'Similar to C# syntax. === for strict equality. Curly braces for blocks.' },
    sameConcept: 'Execute different code paths based on boolean conditions.',
    syntaxDifference: 'Python uses indentation and elif. C#/JS use braces and else if.',
    runtimeDifference: 'Same logical evaluation, different syntax for boolean operators.',
    typeSystemDifference: 'Python: truthy/falsy (0, "", None are falsy). JS: similar. C#: must be bool.',
    typicalUseCase: 'Validation, authorization checks, state machine transitions.',
    erpUseCase: 'if order.state == "draft" and user.has_permission("confirm"): confirm_order()',
  },
  {
    concept: 'Loop',
    python: { code: 'for line in order_lines:\n    total += line.quantity * line.price\n\nfor i in range(10):\n    print(i)', notes: 'for...in iterates any iterable. range() generates number sequences.' },
    csharp: { code: 'foreach (var line in orderLines)\n{\n    total += line.Quantity * line.Price;\n}\n\nfor (int i = 0; i < 10; i++)\n{\n    Console.WriteLine(i);\n}', notes: 'foreach for collections. Traditional for with index counter.' },
    javascript: { code: 'for (const line of orderLines) {\n    total += line.quantity * line.price;\n}\n\norderLines.forEach(line => {\n    total += line.quantity * line.price;\n});', notes: 'for...of for iterables. Array.forEach with arrow function.' },
    sameConcept: 'Repeat code for each item in a collection or range.',
    syntaxDifference: 'Python: for x in collection. C#: foreach. JS: for...of or .forEach().',
    runtimeDifference: 'All iterate collections, but internal mechanism differs (iterator protocol vs enumerator).',
    typeSystemDifference: 'C# foreach is type-safe. Python/JS are dynamically typed in loops.',
    typicalUseCase: 'Processing order lines, batch operations, report generation.',
    erpUseCase: 'for line in self.order_line: compute subtotal, check stock, apply taxes.',
  },
  {
    concept: 'Function',
    python: { code: 'def calculate_total(qty, price, tax_rate=0.05):\n    subtotal = qty * price\n    return subtotal * (1 + tax_rate)\n\nresult = calculate_total(10, 99.50)', notes: 'def keyword. Default parameters. return sends value back.' },
    csharp: { code: 'public decimal CalculateTotal(int qty, decimal price, decimal taxRate = 0.05m)\n{\n    var subtotal = qty * price;\n    return subtotal * (1 + taxRate);\n}\n\nvar result = CalculateTotal(10, 99.50m);', notes: 'Access modifier, return type, typed parameters. Default values supported.' },
    javascript: { code: 'function calculateTotal(qty, price, taxRate = 0.05) {\n    const subtotal = qty * price;\n    return subtotal * (1 + taxRate);\n}\n\nconst result = calculateTotal(10, 99.50);', notes: 'function keyword or arrow: const calc = (qty, price) => qty * price' },
    sameConcept: 'Reusable block of code with parameters and return value.',
    syntaxDifference: 'Python: def. C#: typed signature with braces. JS: function or arrow syntax.',
    runtimeDifference: 'Python/JS create functions at runtime. C# compiles them into IL methods.',
    typeSystemDifference: 'C# enforces parameter and return types. Python/JS do not (unless type hints).',
    typicalUseCase: 'Business calculations, data transformations, validation logic.',
    erpUseCase: 'Odoo model methods: def action_confirm(self): — functions that operate on recordsets.',
  },
  {
    concept: 'Class',
    python: { code: 'class SaleOrder:\n    def __init__(self, partner, lines):\n        self.partner = partner\n        self.lines = lines\n        self.state = "draft"\n\n    def confirm(self):\n        self.state = "confirmed"', notes: 'self is the instance reference. __init__ is the constructor.' },
    csharp: { code: 'public class SaleOrder\n{\n    public string Partner { get; set; }\n    public List<OrderLine> Lines { get; set; }\n    public string State { get; set; } = "draft";\n\n    public void Confirm() => State = "confirmed";\n}', notes: 'Properties with get/set. Auto-property syntax. Expression-bodied methods.' },
    javascript: { code: 'class SaleOrder {\n    constructor(partner, lines) {\n        this.partner = partner;\n        this.lines = lines;\n        this.state = "draft";\n    }\n\n    confirm() {\n        this.state = "confirmed";\n    }\n}', notes: 'ES6 class syntax. constructor replaces __init__. this for instance reference.' },
    sameConcept: 'Blueprint combining data (attributes) and behavior (methods).',
    syntaxDifference: 'Python: class with __init__ and self. C#: properties and access modifiers. JS: constructor and this.',
    runtimeDifference: 'All use prototype-based or class-based OOP under the hood with different mechanisms.',
    typeSystemDifference: 'C# classes are compile-time contracts. Python/JS classes are runtime objects.',
    typicalUseCase: 'Modeling business entities: orders, customers, products, invoices.',
    erpUseCase: 'Odoo: class SaleOrder(models.Model) — every ERP entity is a class with ORM integration.',
  },
  {
    concept: 'Exception Handling',
    python: { code: 'try:\n    result = process_order(order)\nexcept ValueError as e:\n    logger.error(f"Validation failed: {e}")\n    raise\nexcept PermissionError:\n    return {"error": "Unauthorized"}\nfinally:\n    cleanup_temp_data()', notes: 'try/except/finally. raise re-throws. Specific exception types.' },
    csharp: { code: 'try\n{\n    var result = ProcessOrder(order);\n}\ncatch (ValidationException ex)\n{\n    _logger.LogError(ex, "Validation failed");\n    throw;\n}\ncatch (UnauthorizedException)\n{\n    return new ErrorResult("Unauthorized");\n}\nfinally\n{\n    CleanupTempData();\n}', notes: 'try/catch/finally. Typed exceptions. throw re-throws.' },
    javascript: { code: 'try {\n    const result = await processOrder(order);\n} catch (error) {\n    if (error.name === "ValidationError") {\n        console.error("Validation failed:", error.message);\n        throw error;\n    }\n    return { error: "Unauthorized" };\n} finally {\n    cleanupTempData();\n}', notes: 'try/catch/finally. async/await compatible. Error objects with name/message.' },
    sameConcept: 'Gracefully handle errors without crashing the entire program.',
    syntaxDifference: 'Python: except. C#/JS: catch. All support finally and re-throwing.',
    runtimeDifference: 'Stack trace format differs. Python traceback vs C# stack trace vs JS error stack.',
    typeSystemDifference: 'C# exceptions are typed classes. Python/JS use exception hierarchy or generic Error.',
    typicalUseCase: 'Validation failures, database errors, API timeouts, permission denied.',
    erpUseCase: 'Odoo raises UserError for business validation, AccessError for permissions.',
  },
  {
    concept: 'Async / API Call',
    python: { code: 'import httpx\n\nasync def fetch_order(order_id):\n    async with httpx.AsyncClient() as client:\n        response = await client.get(\n            f"https://api.erp.com/orders/{order_id}",\n            headers={"Authorization": "Bearer token"}\n        )\n        return response.json()', notes: 'async/await with httpx or aiohttp. asyncio event loop.' },
    csharp: { code: 'public async Task<Order> FetchOrderAsync(int orderId)\n{\n    var response = await _httpClient.GetAsync(\n        $"https://api.erp.com/orders/{orderId}");\n    response.EnsureSuccessStatusCode();\n    return await response.Content.ReadFromJsonAsync<Order>();\n}', notes: 'async/await with Task<T>. HttpClient for HTTP calls. Strongly typed deserialization.' },
    javascript: { code: 'async function fetchOrder(orderId) {\n    const response = await fetch(\n        `https://api.erp.com/orders/${orderId}`,\n        { headers: { Authorization: "Bearer token" } }\n    );\n    if (!response.ok) throw new Error(`HTTP ${response.status}`);\n    return await response.json();\n}', notes: 'async/await with fetch API. Promises under the hood. Browser-native.' },
    sameConcept: 'Non-blocking operations for I/O — HTTP calls, database queries, file reads.',
    syntaxDifference: 'All use async/await but with different HTTP libraries and return types.',
    runtimeDifference: 'Python: asyncio loop. C#: Task-based async. JS: Promise microtask queue.',
    typeSystemDifference: 'C# returns Task<T> (compile-time checked). Python/JS return coroutines/Promises.',
    typicalUseCase: 'Calling external APIs, ERP integrations, webhook processing.',
    erpUseCase: 'Odoo JSON-RPC calls, REST API integrations between ERP and external systems.',
  },
];
