import type { Term } from '@/types';

export const TERMINOLOGY: Term[] = [
  {
    key: 'runtime',
    term: 'Runtime',
    termAr: 'وقت التشغيل',
    simpleMeaning: 'The environment that actually runs your code on the computer.',
    simpleMeaningAr: 'البيئة التي تشغّل شيفرتك فعليًا على الحاسوب.',
    professionalDefinition: 'The execution environment providing infrastructure for code execution, including memory management, I/O handling, and system resource access.',
    professionalDefinitionAr: 'بيئة التنفيذ التي توفّر البنية التحتية لتشغيل الشيفرة بما في ذلك إدارة الذاكرة والإدخال/الإخراج وموارد النظام.',
    example: 'When you type python script.py, the Python runtime (interpreter) executes your code.',
    exampleAr: 'عند كتابة python script.py ينفّذ وقت تشغيل Python (المفسّر) شيفرتك.',
    erpExample: 'Odoo runs on the Python runtime. PostgreSQL has its own query execution runtime.',
    erpExampleAr: 'يعمل Odoo على وقت تشغيل Python. ولـ PostgreSQL وقت تشغيل خاص بتنفيذ الاستعلامات.',
    odooExample: 'Starting Odoo with ./odoo-bin launches the Python runtime with Odoo modules loaded.',
    odooExampleAr: 'تشغيل Odoo عبر ./odoo-bin يطلق وقت تشغيل Python مع تحميل وحدات Odoo.',
    relatedTerms: ['interpreter', 'compiler', 'execution_flow'],
    category: 'Programming Fundamentals',
    categoryAr: 'أساسيات البرمجة',
  },
  {
    key: 'interpreter',
    term: 'Interpreter',
    termAr: 'المفسّر',
    simpleMeaning: 'A program that reads and executes your code line by line, without a separate compile step.',
    simpleMeaningAr: 'برنامج يقرأ شيفرتك وينفّذها سطرًا بسطر دون خطوة ترجمة منفصلة.',
    professionalDefinition: 'Software that directly executes instructions written in a programming language, translating and running code at runtime rather than pre-compiling to machine code.',
    professionalDefinitionAr: 'برمجية تنفّذ تعليمات لغة البرمجة مباشرة بترجمتها وتشغيلها وقت التشغيل بدل ترجمتها مسبقًا إلى شيفرة آلة.',
    example: 'The Python interpreter (python.exe) reads each line of your .py file and executes it immediately.',
    exampleAr: 'مفسّر Python (python.exe) يقرأ كل سطر من ملف .py وينفّذه فورًا.',
    erpExample: 'Odoo modules are loaded and executed by the Python interpreter at server startup.',
    erpExampleAr: 'تُحمَّل وحدات Odoo وتنفَّذ بواسطة مفسّر Python عند إقلاع الخادم.',
    odooExample: 'When you modify an Odoo model and restart the server, the interpreter re-reads your Python files.',
    odooExampleAr: 'عند تعديل نموذج Odoo وإعادة تشغيل الخادم، يعيد المفسّر قراءة ملفات Python.',
    relatedTerms: ['runtime', 'compiler'],
    category: 'Programming Fundamentals',
    categoryAr: 'أساسيات البرمجة',
  },
  {
    key: 'compiler',
    term: 'Compiler',
    termAr: 'المترجم',
    simpleMeaning: 'A program that translates your entire source code into machine code before it runs.',
    simpleMeaningAr: 'برنامج يترجم شيفرتك المصدرية بالكامل إلى شيفرة آلة قبل التشغيل.',
    professionalDefinition: 'A translator that converts source code written in a high-level language into machine code or intermediate bytecode prior to execution, enabling optimization and early error detection.',
    professionalDefinitionAr: 'مترجم يحوّل الشيفرة المصدرية عالية المستوى إلى شيفرة آلة أو bytecode قبل التنفيذ، مما يمكّن التحسين واكتشاف الأخطاء مبكرًا.',
    example: 'C# code is compiled by the Roslyn compiler into IL bytecode, then JIT-compiled by the CLR.',
    exampleAr: 'تُترجم شيفرة C# بواسطة مترجم Roslyn إلى IL ثم JIT عبر CLR.',
    erpExample: 'C# ERP integration services are compiled before deployment. Type errors are caught at build time.',
    erpExampleAr: 'خدمات تكامل ERP بـ C# تُترجم قبل النشر. تُكتشف أخطاء الأنواع وقت البناء.',
    relatedTerms: ['interpreter', 'runtime'],
    category: 'Programming Fundamentals',
    categoryAr: 'أساسيات البرمجة',
  },
  {
    key: 'variable',
    term: 'Variable',
    termAr: 'متغير',
    simpleMeaning: 'A named container that holds a value in the computer\'s memory.',
    simpleMeaningAr: 'حاوية مسماة تحمل قيمة في ذاكرة الحاسوب.',
    professionalDefinition: 'A symbolic name bound to an object in memory during program execution, serving as a reference to stored data that can be read and modified.',
    professionalDefinitionAr: 'اسم رمزي مرتبط بكائن في الذاكرة أثناء التنفيذ، يُستخدم كمرجع لبيانات يمكن قراءتها وتعديلها.',
    example: 'customer_name = "Acme Corp" creates a variable holding the text "Acme Corp".',
    exampleAr: 'customer_name = "Acme Corp" ينشئ متغيرًا يحمل النص Acme Corp.',
    erpExample: 'In a sales order: order_id, partner_name, amount_total, state are all variables/fields.',
    erpExampleAr: 'في أمر بيع: order_id وpartner_name وamount_total وstate كلها متغيرات/حقول.',
    odooExample: 'record.partner_id is a variable referencing a res.partner record in Odoo ORM.',
    odooExampleAr: 'record.partner_id متغير يشير إلى سجل res.partner في ORM لأودو.',
    relatedTerms: ['data_type', 'scope'],
    category: 'Programming Fundamentals',
    categoryAr: 'أساسيات البرمجة',
  },
  {
    key: 'data_type',
    term: 'Data Type',
    termAr: 'نوع البيانات',
    simpleMeaning: 'The kind of value a variable holds — number, text, true/false, list, etc.',
    simpleMeaningAr: 'نوع القيمة التي يحملها المتغير — رقم أو نص أو صح/خطأ أو قائمة وغيرها.',
    professionalDefinition: 'A classification defining the set of possible values and permitted operations for a data object. Types ensure operations are semantically valid.',
    professionalDefinitionAr: 'تصنيف يحدد مجموعة القيم الممكنة والعمليات المسموحة لكائن بيانات لضمان صحة العمليات دلاليًا.',
    example: 'int (whole numbers), float (decimals), str (text), bool (True/False), list, dict.',
    exampleAr: 'int أعداد صحيحة، float عشرية، str نص، bool صح/خطأ، list، dict.',
    erpExample: 'ERP fields have types: quantity (number), name (text), is_active (boolean), order_date (date).',
    erpExampleAr: 'لحقول ERP أنواع: الكمية رقم، الاسم نص، is_active منطقي، order_date تاريخ.',
    odooExample: 'fields.Integer(), fields.Char(), fields.Float(), fields.Boolean(), fields.Many2one().',
    odooExampleAr: 'fields.Integer() وfields.Char() وfields.Float() وfields.Boolean() وfields.Many2one().',
    relatedTerms: ['variable'],
    category: 'Programming Fundamentals',
    categoryAr: 'أساسيات البرمجة',
  },
  {
    key: 'scope',
    term: 'Scope',
    termAr: 'النطاق',
    simpleMeaning: 'The region of code where a variable name is accessible.',
    simpleMeaningAr: 'منطقة الشيفرة التي يكون فيها اسم المتغير قابلًا للوصول.',
    professionalDefinition: 'The textual context determining where a name binding is visible. Python follows LEGB: Local, Enclosing, Global, Built-in.',
    professionalDefinitionAr: 'السياق النصي الذي يحدد أين يكون ربط الاسم مرئيًا. تتبع Python قاعدة LEGB: محلي، محيط، عام، مدمج.',
    example: 'Variables inside a function are local — they exist only while the function runs.',
    exampleAr: 'المتغيرات داخل الدالة محلية — توجد فقط أثناء تشغيل الدالة.',
    erpExample: 'Odoo model method parameters (self, vals) are local to that method call.',
    erpExampleAr: 'معاملات دوال نماذج Odoo (self وvals) محلية لذلك الاستدعاء.',
    relatedTerms: ['variable', 'execution_flow'],
    category: 'Programming Fundamentals',
    categoryAr: 'أساسيات البرمجة',
  },
  {
    key: 'execution_flow',
    term: 'Execution Flow',
    termAr: 'تدفق التنفيذ',
    simpleMeaning: 'The order in which code lines run, including jumps into and out of functions.',
    simpleMeaningAr: 'ترتيب تشغيل أسطر الشيفرة بما في ذلك الدخول والخروج من الدوال.',
    professionalDefinition: 'The sequential path of instruction execution governed by the call stack, control structures, and exception handling mechanisms.',
    professionalDefinitionAr: 'المسار المتسلسل لتنفيذ التعليمات الذي يحكمه مكدس الاستدعاء وهياكل التحكم وآليات الاستثناءات.',
    example: 'Code runs top to bottom. Function calls pause the caller until the function returns.',
    exampleAr: 'تعمل الشيفرة من الأعلى للأسفل. استدعاء الدالة يوقف المستدعي حتى تعود الدالة.',
    erpExample: 'Confirm button → JS handler → RPC call → Python method → ORM write → SQL → response.',
    erpExampleAr: 'زر تأكيد → معالج JS → استدعاء RPC → دالة Python → كتابة ORM → SQL → استجابة.',
    odooExample: 'action_confirm() → write() → _write() → SQL generation → PostgreSQL commit.',
    odooExampleAr: 'action_confirm() → write() → _write() → توليد SQL → تثبيت PostgreSQL.',
    relatedTerms: ['runtime', 'scope'],
    category: 'Programming Fundamentals',
    categoryAr: 'أساسيات البرمجة',
  },
];

export function getTerm(key: string): Term | undefined {
  return TERMINOLOGY.find((t) => t.key === key);
}

export function searchTerms(query: string): Term[] {
  const q = query.toLowerCase();
  return TERMINOLOGY.filter(
    (t) =>
      t.term.toLowerCase().includes(q) ||
      (t.termAr?.includes(query) ?? false) ||
      t.simpleMeaning.toLowerCase().includes(q) ||
      (t.simpleMeaningAr?.includes(query) ?? false) ||
      t.category.toLowerCase().includes(q) ||
      (t.categoryAr?.includes(query) ?? false),
  );
}
