import type { DayCurriculum, TopicKey } from '@/po/types';
import {
  artifact, caseUpdate, decision, deepConcept, exercise, interview, mcq, prompt,
  scenarioQ, steps, table,
} from '@/po/curriculum/helpers';
import { CASE_STUDY, caseStudyDayNarrative } from '@/po/curriculum/case-study';
import { DAY_SUMMARIES } from '@/po/curriculum/roadmap';

type DayDetail = {
  topic: TopicKey;
  terms: string[];
  concepts: [string, string, string, string, string, string, string, string];
  outcome: string;
  problem: string;
  decision: string;
  artifactFields: string[];
};

const DETAILS: Record<number, DayDetail> = {
  2: { topic: 'agile_mindset', terms: ['Agile values', 'empiricism', 'inspection', 'adaptation', 'increment', 'feedback loop'], concepts: ['Why Agile changes decisions', 'The four Agile values', 'Principles as practical choices', 'Empiricism and evidence', 'Small increments and learning', 'Feedback loops with users', 'Outcome thinking over output', 'Adapting Meridian delivery'], outcome: 'learn early whether receiving and stock visibility improve accuracy', problem: 'a 9-month rewrite hid incorrect assumptions until it was too expensive to change', decision: 'deliver and inspect a thin receiving workflow before committing to barcode expansion', artifactFields: ['Current delivery behavior', 'Agile risk', 'Smallest learning Increment', 'Feedback signal', 'Adaptation decision'] },
  3: { topic: 'scrum_framework', terms: ['Scrum Team', 'Sprint', 'Product Goal', 'Sprint Goal', 'Increment', 'Definition of Done'], concepts: ['Scrum theory and purpose', 'The Scrum Team', 'Product Owner accountability', 'Events and their purpose', 'Artifacts and commitments', 'The Sprint as a container', 'Transparency inspection adaptation', 'Applying Scrum at Meridian'], outcome: 'create a usable, inspectable inventory Increment every Sprint', problem: 'people wait for a final design and mistake Scrum events for status meetings', decision: 'use one Sprint Goal around reliable receiving rather than divide the team among unrelated requests', artifactFields: ['Scrum role', 'Event purpose', 'Artifact', 'Commitment', 'Meridian example'] },
  4: { topic: 'roles_collaboration', terms: ['accountability', 'responsibility', 'RACI', 'collaboration', 'authority', 'delegation'], concepts: ['Accountability versus responsibility', 'Product Owner boundaries', 'Developers and technical ownership', 'Scrum Master and facilitation', 'BA UX and project partnerships', 'RACI without bureaucracy', 'Decision escalation', 'Role clarity at Meridian'], outcome: 'make product decisions fast without creating shadow owners', problem: 'the BA, Project Manager, and Product Owner each believe they can order the same work', decision: 'retain one Product Owner for ordering while inviting specialists to provide evidence', artifactFields: ['Decision area', 'Accountable role', 'Contributors', 'Consulted stakeholders', 'Escalation path'] },
  5: { topic: 'vision_strategy', terms: ['product vision', 'strategy', 'Product Goal', 'outcome', 'strategic theme', 'objective'], concepts: ['Vision versus feature list', 'A compelling product vision', 'Strategy as choices', 'Product Goals', 'Outcomes and measures', 'Strategic alignment', 'Communicating direction', 'Horizon vision workshop'], outcome: 'move Meridian toward trusted stock and reliable customer promises', problem: 'the COO asks for a barcode app without agreeing on the operational outcome', decision: 'frame barcode scanning as a possible strategy, not the product vision or goal', artifactFields: ['Vision statement', 'Target users', 'User need', 'Business outcome', 'Product Goal', 'Strategic choices'] },
  6: { topic: 'stakeholders', terms: ['stakeholder map', 'power-interest', 'user', 'customer', 'sponsor', 'communication plan'], concepts: ['Who counts as a stakeholder', 'Users customers sponsors', 'Stakeholder mapping', 'Power interest analysis', 'Listening and discovery', 'Negotiating conflict', 'Communication cadences', 'Meridian stakeholder plan'], outcome: 'align Finance, Warehouse, and Customer Service on a shared value conversation', problem: 'two sponsors disagree about whether speed or auditability should be first', decision: 'make trade-offs visible with evidence and tailor communication without creating separate backlogs', artifactFields: ['Stakeholder', 'Interest', 'Influence', 'Need from product', 'Engagement approach', 'Communication cadence'] },
  7: { topic: 'product_discovery', terms: ['problem hypothesis', 'assumption', 'experiment', 'interview', 'evidence', 'opportunity'], concepts: ['Discovery before delivery', 'Problem framing', 'Assumptions and risks', 'Research questions', 'User interviews', 'Experiments and prototypes', 'Synthesizing evidence', 'Meridian discovery brief'], outcome: 'confirm why receipts are late before selecting a solution', problem: 'barcode scanning is assumed to solve errors even though process timing and data discipline may be the root cause', decision: 'test the receipt-delay hypothesis with observations and sample data before funding a solution', artifactFields: ['Problem statement', 'Target user', 'Assumption', 'Evidence needed', 'Experiment', 'Decision rule'] },
  8: { topic: 'requirements', terms: ['requirement', 'epic', 'feature', 'user story', 'backlog item', 'traceability'], concepts: ['Requirements as needs', 'From outcome to hierarchy', 'Epics and features', 'User stories as slices', 'Non-functional needs', 'Business rules and constraints', 'Avoiding specification overload', 'Meridian backlog hierarchy'], outcome: 'turn sixty unstructured requests into traceable value-oriented work', problem: 'a shared spreadsheet mixes goals, defects, interface ideas, and detailed tasks', decision: 'group requests by outcome and hierarchy before discussing Sprint selection', artifactFields: ['Business outcome', 'Epic', 'Feature', 'Story', 'Constraint or rule', 'Open question'] },
  9: { topic: 'user_stories', terms: ['user story', 'persona', 'INVEST', 'benefit', 'vertical slice', 'conversation'], concepts: ['Stories are promises to converse', 'User role and need', 'Value statements', 'INVEST quality', 'Vertical slicing', 'Story mapping', 'Writing with Developers', 'Horizon story collection'], outcome: 'give warehouse users small usable improvements instead of technical task lists', problem: 'stories such as “build API” and “make screen better” hide user value and cannot be prioritized well', decision: 'write a receiving story around an operator outcome and split it by workflow complexity', artifactFields: ['Story title', 'As a', 'I want', 'So that', 'Acceptance conversation', 'Split rationale'] },
  10: { topic: 'acceptance_criteria', terms: ['acceptance criteria', 'business rule', 'Given When Then', 'example mapping', 'testability', 'ambiguity'], concepts: ['Why acceptance needs evidence', 'Criteria versus requirements', 'Given When Then examples', 'Business rules', 'Happy and exception paths', 'Example mapping conversations', 'Acceptance and Definition of Done', 'Meridian acceptance map'], outcome: 'ensure receipt posting is demonstrably correct and auditable', problem: 'QA cannot determine whether a partially received purchase order is acceptable', decision: 'make valuation and late-posting rules explicit before development begins', artifactFields: ['Story', 'Rule', 'Given', 'When', 'Then', 'Examples', 'Open question'] },
  11: { topic: 'backlog_management', terms: ['Product Backlog', 'ordering', 'emergent', 'refinement', 'transparency', 'backlog item'], concepts: ['The Product Backlog as source of truth', 'Ordering versus a queue', 'Backlog item attributes', 'Keeping it emergent', 'Removing duplicates and stale work', 'Transparency and access', 'Backlog health measures', 'Meridian backlog build'], outcome: 'maintain one trusted decision surface for inventory work', problem: 'duplicate emailed requests and old ideas compete with current operational risks', decision: 'archive invalid items, merge duplicates, and order remaining work against the Product Goal', artifactFields: ['Backlog item', 'Outcome link', 'Order', 'Evidence', 'Status', 'Next refinement action'] },
  12: { topic: 'prioritization', terms: ['prioritization', 'cost of delay', 'risk', 'value', 'WSJF', 'trade-off'], concepts: ['Prioritization is a decision', 'Value and urgency', 'Cost of delay', 'Risk reduction', 'Prioritization methods', 'Sequencing dependencies', 'Saying no and not now', 'Meridian priority rationale'], outcome: 'choose the next work that most improves trusted availability', problem: 'every department labels its own request urgent and asks for equal capacity', decision: 'prioritize receiving accuracy and availability evidence over a dashboard that merely reports bad data', artifactFields: ['Candidate', 'Value', 'Urgency', 'Risk', 'Effort signal', 'Order', 'Rationale'] },
  13: { topic: 'estimation_forecasting', terms: ['estimate', 'forecast', 'capacity', 'velocity', 'range', 'uncertainty'], concepts: ['Estimates are not promises', 'Relative estimation', 'Capacity and availability', 'Velocity as history', 'Forecast ranges', 'Dependencies and risk', 'Communicating uncertainty', 'Meridian release forecast'], outcome: 'offer leadership a credible delivery range for foundational inventory capability', problem: 'leadership wants an exact release date from early estimates and changing scope', decision: 'forecast a range based on capacity and assumptions, and state the conditions that change it', artifactFields: ['Scope hypothesis', 'Capacity', 'Estimate range', 'Assumptions', 'Risk', 'Forecast range', 'Review date'] },
  14: { topic: 'refinement', terms: ['refinement', 'Definition of Ready', 'slicing', 'clarity', 'estimate', 'dependency'], concepts: ['Refinement purpose', 'Readiness versus certainty', 'Collaborative clarification', 'Splitting oversized work', 'Finding dependencies', 'Estimating at the right time', 'Definition of Ready signals', 'Meridian refinement session'], outcome: 'make the next Sprint candidates understandable, valuable, and small enough to plan', problem: 'selected items lack examples, dependencies, and shared understanding', decision: 'return unclear work to refinement rather than carry ambiguity into Sprint Planning', artifactFields: ['Item', 'Value', 'Examples', 'Size signal', 'Dependency', 'Risk', 'Ready decision'] },
  15: { topic: 'sprint_planning', terms: ['Sprint Planning', 'Sprint Goal', 'capacity', 'forecast', 'Sprint Backlog', 'trade-off'], concepts: ['Sprint Planning purpose', 'A coherent Sprint Goal', 'Why before what', 'Capacity-aware selection', 'Developer forecast', 'Negotiating scope', 'Creating a Sprint Backlog', 'Meridian Sprint plan'], outcome: 'deliver a coherent receipt-to-availability slice within actual team capacity', problem: 'stakeholders want five unrelated requests inserted into a Sprint with limited capacity', decision: 'select work that serves one Sprint Goal and transparently defer unrelated requests', artifactFields: ['Sprint Goal', 'Selected items', 'Capacity assumptions', 'Expected value', 'Excluded items', 'Risk', 'Review evidence'] },
  16: { topic: 'sprint_execution', terms: ['Sprint Goal', 'Daily Scrum', 'scope negotiation', 'impediment', 'replanning', 'decision log'], concepts: ['PO availability during Sprint', 'Protecting the Sprint Goal', 'Clarification without micromanagement', 'Mid-Sprint change', 'Urgent defects', 'Daily collaboration', 'Decision logging', 'Meridian execution choices'], outcome: 'keep the team focused while resolving a real receiving defect quickly', problem: 'Customer Service requests a new screen while a receiving bug threatens the Sprint Goal', decision: 'triage the defect against impact, defer the screen request, and make the trade-off visible', artifactFields: ['Date', 'Request or issue', 'Sprint Goal impact', 'Evidence', 'Decision', 'Owner', 'Follow-up'] },
  17: { topic: 'quality_acceptance', terms: ['quality', 'acceptance', 'Definition of Done', 'UAT', 'evidence', 'defect'], concepts: ['Quality is built in', 'Acceptance versus approval', 'Definition of Done', 'Acceptance Criteria evidence', 'UAT roles', 'Defects and trade-offs', 'Auditability and ERP quality', 'Meridian acceptance report'], outcome: 'accept only usable, auditable receipt functionality that meets critical rules', problem: 'a demonstration looks complete but permits a stock movement without the required finance audit trail', decision: 'reject the affected backlog item until the critical rule has evidence of passing', artifactFields: ['Increment', 'Criteria', 'Evidence', 'Pass or fail', 'Defect severity', 'Acceptance decision', 'Follow-up'] },
  18: { topic: 'review_retrospective', terms: ['Sprint Review', 'retrospective', 'feedback', 'adaptation', 'action', 'inspection'], concepts: ['Review and retrospective differ', 'Inspecting the Increment', 'Inviting useful feedback', 'Outcome evidence', 'Retrospective safety', 'Improvement experiments', 'Adapting backlog and process', 'Meridian improvement report'], outcome: 'use live warehouse feedback to adapt both backlog order and refinement practice', problem: 'review attendees request conflicting changes while the team repeats vague-story rework', decision: 'separate product feedback from process improvement, then create owned experiments for both', artifactFields: ['Observed outcome', 'Feedback', 'Backlog adaptation', 'Process insight', 'Experiment', 'Owner', 'Review date'] },
  19: { topic: 'roadmaps_metrics', terms: ['roadmap', 'release', 'MVP', 'metric', 'leading indicator', 'outcome'], concepts: ['Roadmaps communicate direction', 'Outcome-based roadmap themes', 'Release planning', 'MVP and MMP', 'Product metrics', 'Leading and lagging measures', 'Metric ethics and trade-offs', 'Meridian roadmap framework'], outcome: 'communicate a credible path from receipt accuracy to reliable customer promises', problem: 'leadership asks for a date-heavy roadmap with no outcome measures or learning checkpoints', decision: 'publish theme-based horizons with release hypotheses and metrics rather than fixed feature promises', artifactFields: ['Horizon', 'Outcome', 'Theme', 'Release hypothesis', 'Metric', 'Assumption', 'Review trigger'] },
  20: { topic: 'professional_practice', terms: ['product strategy', 'discovery', 'backlog', 'stakeholder management', 'evidence', 'professional judgment'], concepts: ['End-to-end Product Ownership', 'Diagnosing an unclear request', 'Strategy and discovery integration', 'Backlog and prioritization choices', 'Sprint and acceptance leadership', 'Stakeholder communication', 'Metrics and adaptation', 'Professional simulation debrief'], outcome: 'make a defensible end-to-end decision about AI warehouse planning', problem: 'a sponsor asks for AI without a defined user problem, evidence, outcome, or delivery trade-off', decision: 'treat AI as a hypothesis, run discovery, and protect foundational inventory work until evidence justifies change', artifactFields: ['Request', 'Problem hypothesis', 'Evidence plan', 'Product Goal link', 'Backlog decision', 'Stakeholder message', 'Success metric'] },
};

export function createFullDay(dayNumber: number): DayCurriculum {
  const summary = DAY_SUMMARIES.find((item) => item.dayNumber === dayNumber);
  const detail = DETAILS[dayNumber];
  if (!summary || !detail) throw new Error(`No full curriculum configured for day ${dayNumber}`);
  const topic = detail.topic;

  const sections = detail.concepts.map((concept, index) => deepConcept({
    id: `d${dayNumber}-s${index + 1}`,
    title: concept,
    titleAr: `المفهوم ${index + 1}: ${summary.titleAr}`,
    type: index === 3 ? 'process' : index === 5 ? 'worked_example' : 'theory',
    content: {
      conceptIntroduction: `${concept} is a distinct Product Owner capability within ${summary.title}. It gives you a way to make a deliberate decision instead of reacting to the loudest request.`,
      simpleExplanation: `In plain language, use ${concept.toLowerCase()} to help Meridian learn what improves the product, then make the next choice visible.`,
      businessProblem: `Meridian needs to ${detail.outcome}. Today, ${detail.problem}.`,
      professionalDefinition: `${concept} is applied deliberately: the Product Owner gathers relevant evidence, makes the value trade-off explicit, and aligns the Product Backlog or team conversation with the Product Goal.`,
      whyImportant: `Without this practice, Horizon ERP risks delivering activity rather than value and stakeholders cannot understand why work is ordered.`,
      lifecycleLocation: `It is used before delivery to shape decisions, during delivery to clarify trade-offs, and after delivery to inspect whether ${detail.outcome}.`,
      howItWorks: `1) State the decision. 2) Identify users and evidence. 3) Connect the decision to the Product Goal. 4) Compare alternatives and constraints. 5) Communicate the decision and inspect its result.`,
      whoResponsible: 'The Product Owner owns the product-value decision. Developers, users, and specialists contribute evidence and options.',
      whoParticipates: 'Warehouse operators, Inventory Control, Customer Service, Finance, Developers, and the Scrum Master participate according to the question.',
      requiredInputs: 'Product Goal, user evidence, operational data, constraints, stakeholder input, and the current ordered Product Backlog.',
      activities: `Analyze the current situation, discuss ${concept.toLowerCase()} with collaborators, make a visible decision, and update the relevant product artifact.`,
      expectedOutputs: `${summary.artifactName}, a clearer Product Backlog decision, and a shared explanation of how the choice supports ${detail.outcome}.`,
      simpleExample: `A shop owner observes that customers leave because the queue is slow, tests a simpler checkout step, and keeps it only if waiting time falls.`,
      softwareExample: 'A team releases a small workflow, observes completion and support signals, then improves the highest-friction step instead of building every requested option.',
      erpExample: `${CASE_STUDY.productName} Inventory & Warehouse uses ${concept.toLowerCase()} to improve late receipt handling, stock truth, and customer promise reliability at ${CASE_STUDY.companyName}.`,
      workedExample: `Meridian situation: ${detail.problem}\nPO decision: ${detail.decision}.\nEvidence to inspect: receipt timestamps, cycle-count variance, and operator feedback.\nExpected learning: whether the selected action advances ${detail.outcome}.`,
      comparison: `A professional Product Owner distinguishes evidence from opinion, an outcome from an output, and a decision from an unexamined request when applying ${concept.toLowerCase()}.`,
      commonMisunderstandings: `Misunderstanding: ${concept} means completing a document or meeting. Correction: it is valuable only when it changes a product decision using evidence.`,
      beginnerMistakes: [
        { wrong: 'Treating the first suggested solution as the requirement', right: 'State the user problem and desired outcome before selecting a solution', explanation: 'This preserves options and prevents expensive rework.' },
        { wrong: 'Recording a decision without the reason', right: 'Capture evidence, trade-off, and review point', explanation: 'Stakeholders can then challenge assumptions productively.' },
      ],
      workplaceMistakes: [
        { wrong: 'Allowing each department to maintain its own priority list', right: 'Use one transparent Product Backlog and communicate the ordering rationale', explanation: 'Competing hidden lists destroy focus and trust.' },
      ],
      poorExample: `“${concept} is urgent, so build it now.”`,
      correctExample: `“We will ${detail.decision} because it best supports ${detail.outcome}; we will inspect the agreed evidence at the next Sprint Review.”`,
      guidedPractice: `Use the Meridian narrative to identify the evidence required before applying ${concept.toLowerCase()}.`,
      independentPractice: `Write and defend a Product Owner decision that applies ${concept.toLowerCase()} to one Horizon ERP backlog item.`,
      scenarioDecision: `Finance requests more controls while Warehouse requests speed. Use ${concept.toLowerCase()} to make the trade-off transparent rather than promising both immediately.`,
      reflectionQuestion: `What evidence would make you change your Meridian decision about ${concept.toLowerCase()}?`,
      professionalTerminology: `Use “evidence,” “outcome,” “Product Goal,” “trade-off,” and the topic terms precisely; avoid calling every stakeholder request a commitment.`,
      interviewQuestion: `How would you apply ${concept.toLowerCase()} as Product Owner for an ERP product?`,
      interviewModelAnswer: `I would begin with the operational problem and target outcome, involve the people who hold evidence, and make the Product Backlog decision transparent. For Meridian, I would ${detail.decision}, inspect the result, and adapt rather than treat the initial request as a fixed commitment.`,
      comparisonTable: index === 0 ? table(
        `${summary.title}: decision comparison`,
        ['Approach', 'What happens', 'Product Owner risk', 'Better practice'],
        [
          ['React to the loudest request', 'Busy Sprint, unclear value', 'Shadow priorities and rework', 'Order by Product Goal evidence'],
          ['Freeze a full solution early', 'Delayed learning', 'Wrong solution at high cost', 'Inspect a thin Increment first'],
          ['Document without deciding', 'Meetings without trade-offs', 'No one owns the outcome', 'Decide, communicate, review'],
          [detail.decision, `Advances ${detail.outcome}`, 'Managed if evidence is inspected', 'Keep the decision transparent'],
        ],
      ) : undefined,
      processSteps: index === 3 ? steps(
        { id: `d${dayNumber}-p1`, label: 'Frame the decision', description: `State the Meridian problem: ${detail.problem}` },
        { id: `d${dayNumber}-p2`, label: 'Gather evidence', description: 'Collect user observation, operational data, and stakeholder constraints.' },
        { id: `d${dayNumber}-p3`, label: 'Compare options', description: 'Evaluate alternatives against the Product Goal and risks.' },
        { id: `d${dayNumber}-p4`, label: 'Decide and communicate', description: detail.decision },
        { id: `d${dayNumber}-p5`, label: 'Inspect and adapt', description: `Review whether work advances ${detail.outcome}.` },
      ) : undefined,
    },
    requiresAnswer: prompt(
      `Apply ${concept} to Meridian in 4–6 sentences. Name a user, evidence, a Product Owner decision, and the outcome you will inspect.`,
      'write',
      `For Meridian, I would use ${concept.toLowerCase()} with Warehouse and Customer Service evidence. I would ${detail.decision}. This supports ${detail.outcome}; I would inspect receipt timing, inventory accuracy, and user feedback before expanding scope.`,
      'Use user, evidence, decision, and outcome',
      ['Meridian', 'evidence', 'decision', 'outcome'],
    ),
  }));

  const quiz = detail.concepts.map((concept, index) => mcq(
    `d${dayNumber}-q${index + 1}`, topic,
    `Which Product Owner action best demonstrates ${concept.toLowerCase()} at Meridian?`,
    ['Commit to the first executive request without evidence', 'Use evidence and the Product Goal to make and communicate a trade-off', 'Ask every department to maintain a separate priority list', 'Wait for a complete fixed specification before learning'],
    'Use evidence and the Product Goal to make and communicate a trade-off',
    `${concept} requires an evidence-based product decision. It does not mean automatic commitment, fragmented ordering, or delaying learning until certainty exists.`,
  ));
  quiz.push(mcq(`d${dayNumber}-q9`, topic, `What should the Product Owner inspect after applying ${summary.title}?`, ['Whether every stakeholder is equally happy', 'Outcome evidence related to the Product Goal', 'Only whether the document was completed', 'Only individual developer utilization'], 'Outcome evidence related to the Product Goal', 'Product work is judged by value and learning, not document completion or local utilization.'));
  quiz.push(mcq(`d${dayNumber}-q10`, topic, 'When stakeholders conflict, what is the strongest response?', ['Promise all requests this Sprint', 'Explain an evidence-based order and review point', 'Let the loudest person decide', 'Hide the decision until release'], 'Explain an evidence-based order and review point', 'Transparent rationale preserves relationships while protecting product focus.'));

  const exam = Array.from({ length: 5 }, (_, index) => scenarioQ(
    `d${dayNumber}-e${index + 1}`, topic,
    `Scenario ${index + 1}: ${caseStudyDayNarrative(dayNumber)} A senior stakeholder demands an immediate solution that conflicts with current evidence. What should you do?`,
    ['Commit immediately to avoid conflict', 'Clarify the problem, compare it to the Product Goal and evidence, order it transparently, and communicate the trade-off', 'Ask Developers to decide product priority alone', 'Ignore the stakeholder request'],
    'Clarify the problem, compare it to the Product Goal and evidence, order it transparently, and communicate the trade-off',
    `A capable Product Owner respects the request without confusing it with a commitment. The right response protects ${detail.outcome} through evidence and transparent ordering.`,
    20,
  ));

  return {
    dayNumber, title: summary.title, titleAr: summary.titleAr, subtitle: summary.subtitle, subtitleAr: summary.subtitleAr,
    difficulty: summary.difficulty, estimatedHours: summary.estimatedHours,
    prerequisites: [`Complete Day ${dayNumber - 1} and review its artifact`, 'Bring the Meridian case study notes forward'],
    topics: [topic],
    objectives: [`Explain and apply ${summary.title}`, `Make an evidence-based Product Owner decision for Horizon ERP`, `Produce a ${summary.artifactName}`, 'Handle stakeholder conflict with a transparent rationale', 'Pass a topic-specific quiz and scenario exam'],
    objectivesAr: [`شرح وتطبيق ${summary.titleAr}`, 'اتخاذ قرار مالك منتج قائم على الأدلة لـ Horizon ERP', `إنتاج ${summary.artifactName}`, 'إدارة تعارض أصحاب المصلحة بمنطق واضح', 'اجتياز الاختبار والامتحان القائم على السيناريو'],
    keyTerminology: detail.terms,
    sections,
    productOwnerResponsibility: ['Own Product Backlog ordering', 'Maximize value toward the Product Goal', 'Make trade-offs transparent', 'Seek evidence from users and stakeholders', 'Communicate and adapt product decisions'],
    notProductOwnerResponsibility: ['Micromanage Developers’ implementation tasks', 'Promise every request or fixed scope without trade-offs', 'Replace the Scrum Master as process coach', 'Maintain private competing priority lists', 'Accept work without agreed evidence'],
    guidedExercise: exercise({ id: `d${dayNumber}-guided`, title: `${summary.title}: guided Meridian application`, instructions: `Use the case narrative to create the first two rows of your ${summary.artifactName}. State the problem, target outcome, evidence, and a Product Owner decision.`, hints: ['Start with the user problem, not a feature', 'Connect your decision to a measurable outcome', 'Write what evidence could change your mind'], modelAnswer: `Problem: ${detail.problem}\nOutcome: ${detail.outcome}\nDecision: ${detail.decision}\nEvidence: receipt timing, cycle counts, and user observation.\nReview: inspect the evidence at Sprint Review before expanding scope.`, scoringCriteria: ['Names a Meridian user and problem', 'States an outcome', 'Makes an explicit trade-off', 'Names inspectable evidence'], difficulty: 'guided' }),
    independentExercise: exercise({ id: `d${dayNumber}-independent`, title: `${summary.title}: independent decision`, instructions: `Finance asks for an audit report while Warehouse asks for speed. Apply today’s topic to choose what comes next, document what you defer, and draft a six-sentence stakeholder reply.`, modelAnswer: `I will prioritize the work with the strongest evidence of advancing ${detail.outcome}. I will document the other request as deferred, not rejected, with its assumptions and review trigger. I will explain the choice to Finance and Warehouse using the Product Goal, the operational risk, and the evidence we will inspect.`, scoringCriteria: ['Uses topic-specific reasoning', 'States a choice and a deferral', 'Uses evidence and Product Goal', 'Professional stakeholder communication'], difficulty: dayNumber >= 16 ? 'professional' : 'independent' }),
    stakeholderScenario: decision({ id: `d${dayNumber}-stakeholder`, title: 'Competing Meridian demands', context: caseStudyDayNarrative(dayNumber), conflict: 'Warehouse wants speed, Finance wants audit certainty, and Customer Service wants availability answers immediately; capacity covers only one focused slice.', question: 'How will you respond as Product Owner?', options: ['Add all demands to the Sprint', 'Use evidence and the Product Goal to order one slice, document the trade-off, and communicate a review point', 'Choose the most senior stakeholder’s request without analysis', 'Ask the team to keep three secret lists'], modelAnswer: 'Use evidence and the Product Goal to order one slice, document the trade-off, and communicate a review point', feedbackRubric: ['Protects one transparent Product Backlog', 'Makes a clear trade-off', 'Connects choice to outcome evidence', 'Communicates respectfully'] }),
    productDecisionChallenge: decision({ id: `d${dayNumber}-decision`, title: 'Defend the next decision', context: `The current evidence is incomplete, but leadership asks for a final answer about ${summary.title}.`, conflict: 'A quick promise may please leadership today but could send the team toward the wrong solution.', question: 'What decision do you make now?', modelAnswer: `I will ${detail.decision}. I will be explicit about the evidence and assumptions, keep the alternative visible in the Product Backlog, and review the decision against ${detail.outcome}.`, feedbackRubric: ['Clear decision', 'Evidence and assumptions named', 'Trade-off visible', 'Adaptation trigger included'] }),
    artifactActivity: artifact({ id: `d${dayNumber}-artifact`, title: summary.artifactName, description: `Create a working ${summary.artifactName} for Horizon ERP Inventory & Warehouse.`, template: `# ${summary.artifactName}\n${detail.artifactFields.map((field) => `${field}:`).join('\n')}\n`, instructions: 'Complete every field with specific Meridian evidence. Do not paste generic Agile language; show the decision and its review condition.', modelArtifact: `# ${summary.artifactName}\n${detail.artifactFields[0]}: ${detail.problem}\n${detail.artifactFields[1]}: ${detail.outcome}\n${detail.artifactFields[2]}: Warehouse Operator and Customer Service Agent\n${detail.artifactFields[3]}: ${detail.decision}\n${detail.artifactFields[4]}: Receipt timestamps, cycle-count variance, and user observation\n${detail.artifactFields[5] ?? 'Review'}: Inspect at the next Sprint Review\n`, scoringCriteria: ['All required fields completed', 'Meridian-specific evidence', 'Outcome-based decision', 'Explicit trade-off', 'Review condition included'], requiredFields: detail.artifactFields.map((field) => `${field}:`) }),
    caseStudyUpdate: caseUpdate({ dayFocus: summary.title, narrative: caseStudyDayNarrative(dayNumber), newInformation: `A sponsor says: “Skip analysis. I need this solution now.” Warehouse operators report that ${detail.problem}.`, requiredAction: 'Draft a professional reply that acknowledges urgency, states the evidence-based next action, and explains what will be inspected.', modelResponse: `Thank you for raising the urgency. I will treat the requested solution as an important input, not an automatic commitment. The current product concern is that ${detail.problem}. To advance ${detail.outcome}, I will ${detail.decision}. I will share the evidence, trade-off, and review point with Finance, Warehouse, and Customer Service so we can adapt based on results rather than assumptions.` }),
    quiz, exam,
    interviewPrep: interview({ question: `How have you used ${summary.title} to make a difficult Product Owner decision?`, modelAnswer: `I begin with the user and business problem, then identify the outcome and evidence that matter. In Meridian’s Horizon ERP product, ${detail.problem}. I would ${detail.decision} because it supports ${detail.outcome}. I make the trade-off visible in ${summary.artifactName}, communicate it to stakeholders, and inspect results before expanding the solution.`, followUps: ['How did you handle disagreement?', 'What evidence would change your mind?', 'What did you defer and why?'], scoringCriteria: ['Explains the concept accurately', 'Uses a specific ERP example', 'Makes a trade-off explicit', 'Includes evidence and adaptation'] }),
    lessonSummary: [`${summary.title} supports a real Product Owner decision, not paperwork.`, `Meridian focus: ${detail.outcome}.`, 'Evidence, user needs, and the Product Goal guide trade-offs.', 'One transparent Product Backlog prevents political prioritization.', `The day artifact is ${summary.artifactName}.`, 'Inspect results and adapt rather than defend assumptions.'],
    revisionChecklist: ['Read all eight concepts', 'Answer active-learning prompts', 'Complete guided exercise', 'Complete independent exercise', 'Submit the artifact', 'Resolve stakeholder scenario', 'Attempt all ten quiz questions', 'Attempt all five exam scenarios', 'Practice interview response'],
    additionalPractice: exercise({ id: `d${dayNumber}-teachback`, title: `${summary.title}: teach-back`, instructions: `Teach a new Product Owner how to apply today’s topic at Meridian. Include the problem, outcome, decision, common mistake, and evidence loop.`, modelAnswer: `A strong teach-back explains that ${summary.title} is used to make an evidence-based choice. At Meridian, ${detail.problem}; the PO should ${detail.decision} to pursue ${detail.outcome}, then inspect real operational evidence and adapt.`, scoringCriteria: ['Plain-language explanation', 'Specific Meridian example', 'Decision and outcome', 'Evidence loop'], difficulty: 'independent' }),
    professionalFeedbackNotes: ['Generic statements score poorly; use the Meridian facts.', 'A request is not a commitment until the Product Owner orders it.', 'Name what you will inspect, not just what you will build.', 'Show the trade-off and how stakeholders will hear it.', 'Use the product artifact as a living decision record.'],
  };
}
