import type { DayCurriculum, TopicKey } from '@/po/types';
import {
  artifact, caseUpdate, decision, deepConcept, exercise, interview, mcq, prompt,
  scenarioQ, steps, table,
} from '@/po/curriculum/helpers';
import { CASE_STUDY, caseStudyDayNarrative, caseStudyDayNarrativeAr } from '@/po/curriculum/case-study';
import { DAY_SUMMARIES } from '@/po/curriculum/roadmap';

type DayDetail = {
  topic: TopicKey;
  terms: string[];
  concepts: [string, string, string, string, string, string, string, string];
  conceptsAr: [string, string, string, string, string, string, string, string];
  outcome: string;
  outcomeAr: string;
  problem: string;
  problemAr: string;
  decision: string;
  decisionAr: string;
  artifactFields: string[];
  artifactFieldsAr: string[];
  artifactNameAr: string;
};

const DETAILS: Record<number, DayDetail> = {
  2: {
    topic: 'agile_mindset',
    terms: ['Agile values', 'empiricism', 'inspection', 'adaptation', 'increment', 'feedback loop'],
    concepts: ['Why Agile changes decisions', 'The four Agile values', 'Principles as practical choices', 'Empiricism and evidence', 'Small increments and learning', 'Feedback loops with users', 'Outcome thinking over output', 'Adapting Meridian delivery'],
    conceptsAr: ['لماذا تغيّر أجايل القرارات', 'قيم أجايل الأربع', 'المبادئ كاختيارات عملية', 'التجريبية والأدلة', 'زيادات صغيرة والتعلم', 'حلقات التغذية الراجعة مع المستخدمين', 'التفكير بالنتيجة لا بالمخرج', 'تكييف تسليم ميريديان'],
    outcome: 'learn early whether receiving and stock visibility improve accuracy',
    outcomeAr: 'التعلم مبكرًا مما إذا كان الاستلام ورؤية المخزون يحسّنان الدقة',
    problem: 'a 9-month rewrite hid incorrect assumptions until it was too expensive to change',
    problemAr: 'إعادة كتابة استمرت 9 أشهر أخفت افتراضات خاطئة حتى أصبح التغيير مكلفًا جدًا',
    decision: 'deliver and inspect a thin receiving workflow before committing to barcode expansion',
    decisionAr: 'تسليم وفحص سير عمل استلام رفيع قبل الالتزام بتوسيع الباركود',
    artifactFields: ['Current delivery behavior', 'Agile risk', 'Smallest learning Increment', 'Feedback signal', 'Adaptation decision'],
    artifactFieldsAr: ['سلوك التسليم الحالي', 'مخاطر أجايل', 'أصغر زيادة للتعلم', 'إشارة التغذية الراجعة', 'قرار التكييف'],
    artifactNameAr: 'خطة تحويل التسليم بأجايل',
  },
  3: {
    topic: 'scrum_framework',
    terms: ['Scrum Team', 'Sprint', 'Product Goal', 'Sprint Goal', 'Increment', 'Definition of Done'],
    concepts: ['Scrum theory and purpose', 'The Scrum Team', 'Product Owner accountability', 'Events and their purpose', 'Artifacts and commitments', 'The Sprint as a container', 'Transparency inspection adaptation', 'Applying Scrum at Meridian'],
    conceptsAr: ['نظرية سكرم والغرض منها', 'فريق سكرم', 'مساءلة مالك المنتج', 'الأحداث وغرضها', 'المخرجات والالتزامات', 'السباق كحاوية', 'الشفافية والفحص والتكييف', 'تطبيق سكرم في ميريديان'],
    outcome: 'create a usable, inspectable inventory Increment every Sprint',
    outcomeAr: 'إنشاء زيادة مخزون قابلة للاستخدام والفحص في كل سباق',
    problem: 'people wait for a final design and mistake Scrum events for status meetings',
    problemAr: 'ينتظر الناس تصميمًا نهائيًا ويخلطون أحداث سكرم باجتماعات الحالة',
    decision: 'use one Sprint Goal around reliable receiving rather than divide the team among unrelated requests',
    decisionAr: 'استخدام هدف سباق واحد حول الاستلام الموثوق بدل تقسيم الفريق بين طلبات غير مرتبطة',
    artifactFields: ['Scrum role', 'Event purpose', 'Artifact', 'Commitment', 'Meridian example'],
    artifactFieldsAr: ['دور سكرم', 'غرض الحدث', 'المخرج', 'الالتزام', 'مثال ميريديان'],
    artifactNameAr: 'خريطة إطار عمل سكرم الكاملة',
  },
  4: {
    topic: 'roles_collaboration',
    terms: ['accountability', 'responsibility', 'RACI', 'collaboration', 'authority', 'delegation'],
    concepts: ['Accountability versus responsibility', 'Product Owner boundaries', 'Developers and technical ownership', 'Scrum Master and facilitation', 'BA UX and project partnerships', 'RACI without bureaucracy', 'Decision escalation', 'Role clarity at Meridian'],
    conceptsAr: ['المساءلة مقابل المسؤولية', 'حدود مالك المنتج', 'المطورون والملكية التقنية', 'سكرم ماستر والتيسير', 'شراكات محلل الأعمال وUX والمشروع', 'RACI بلا بيروقراطية', 'تصعيد القرار', 'وضوح الأدوار في ميريديان'],
    outcome: 'make product decisions fast without creating shadow owners',
    outcomeAr: 'اتخاذ قرارات المنتج بسرعة دون إنشاء مالكين ظل',
    problem: 'the BA, Project Manager, and Product Owner each believe they can order the same work',
    problemAr: 'محلل الأعمال ومدير المشروع ومالك المنتج يعتقد كل منهم أنه يرتب نفس العمل',
    decision: 'retain one Product Owner for ordering while inviting specialists to provide evidence',
    decisionAr: 'الإبقاء على مالك منتج واحد للترتيب مع دعوة المتخصصين لتقديم الأدلة',
    artifactFields: ['Decision area', 'Accountable role', 'Contributors', 'Consulted stakeholders', 'Escalation path'],
    artifactFieldsAr: ['مجال القرار', 'الدور المسؤول', 'المساهمون', 'أصحاب المصلحة المستشارون', 'مسار التصعيد'],
    artifactNameAr: 'مصفوفة مسؤوليات فريق المنتج',
  },
  5: {
    topic: 'vision_strategy',
    terms: ['product vision', 'strategy', 'Product Goal', 'outcome', 'strategic theme', 'objective'],
    concepts: ['Vision versus feature list', 'A compelling product vision', 'Strategy as choices', 'Product Goals', 'Outcomes and measures', 'Strategic alignment', 'Communicating direction', 'Horizon vision workshop'],
    conceptsAr: ['الرؤية مقابل قائمة الميزات', 'رؤية منتج مقنعة', 'الاستراتيجية كاختيارات', 'أهداف المنتج', 'النتائج والمقاييس', 'المواءمة الاستراتيجية', 'إيصال الاتجاه', 'ورشة رؤية Horizon'],
    outcome: 'move Meridian toward trusted stock and reliable customer promises',
    outcomeAr: 'دفع ميريديان نحو مخزون موثوق ووعود عملاء موثوقة',
    problem: 'the COO asks for a barcode app without agreeing on the operational outcome',
    problemAr: 'يطلب المدير التشغيلي تطبيق باركود دون الاتفاق على النتيجة التشغيلية',
    decision: 'frame barcode scanning as a possible strategy, not the product vision or goal',
    decisionAr: 'اعتبار مسح الباركود استراتيجية محتملة لا رؤية المنتج أو هدفه',
    artifactFields: ['Vision statement', 'Target users', 'User need', 'Business outcome', 'Product Goal', 'Strategic choices'],
    artifactFieldsAr: ['بيان الرؤية', 'المستخدمون المستهدفون', 'حاجة المستخدم', 'نتيجة العمل', 'هدف المنتج', 'الاختيارات الاستراتيجية'],
    artifactNameAr: 'لوحة رؤية المنتج وهدف المنتج',
  },
  6: {
    topic: 'stakeholders',
    terms: ['stakeholder map', 'power-interest', 'user', 'customer', 'sponsor', 'communication plan'],
    concepts: ['Who counts as a stakeholder', 'Users customers sponsors', 'Stakeholder mapping', 'Power interest analysis', 'Listening and discovery', 'Negotiating conflict', 'Communication cadences', 'Meridian stakeholder plan'],
    conceptsAr: ['من يُعد صاحب مصلحة', 'المستخدمون والعملاء والراعون', 'رسم خريطة أصحاب المصلحة', 'تحليل القوة والاهتمام', 'الاستماع والاكتشاف', 'التفاوض عند التعارض', 'إيقاعات التواصل', 'خطة أصحاب المصلحة في ميريديان'],
    outcome: 'align Finance, Warehouse, and Customer Service on a shared value conversation',
    outcomeAr: 'مواءمة المالية والمستودع وخدمة العملاء حول حوار قيمة مشترك',
    problem: 'two sponsors disagree about whether speed or auditability should be first',
    problemAr: 'راعيا المشروع يختلفان حول أولوية السرعة أو قابلية التدقيق',
    decision: 'make trade-offs visible with evidence and tailor communication without creating separate backlogs',
    decisionAr: 'إظهار المقايضات بالأدلة وتخصيص التواصل دون إنشاء قوائم مهام منفصلة',
    artifactFields: ['Stakeholder', 'Interest', 'Influence', 'Need from product', 'Engagement approach', 'Communication cadence'],
    artifactFieldsAr: ['صاحب المصلحة', 'الاهتمام', 'التأثير', 'الحاجة من المنتج', 'أسلوب التفاعل', 'إيقاع التواصل'],
    artifactNameAr: 'خريطة أصحاب المصلحة وخطة التواصل',
  },
  7: {
    topic: 'product_discovery',
    terms: ['problem hypothesis', 'assumption', 'experiment', 'interview', 'evidence', 'opportunity'],
    concepts: ['Discovery before delivery', 'Problem framing', 'Assumptions and risks', 'Research questions', 'User interviews', 'Experiments and prototypes', 'Synthesizing evidence', 'Meridian discovery brief'],
    conceptsAr: ['الاكتشاف قبل التسليم', 'صياغة المشكلة', 'الافتراضات والمخاطر', 'أسئلة البحث', 'مقابلات المستخدمين', 'التجارب والنماذج الأولية', 'تركيب الأدلة', 'موجز اكتشاف ميريديان'],
    outcome: 'confirm why receipts are late before selecting a solution',
    outcomeAr: 'تأكيد سبب تأخر الإيصالات قبل اختيار الحل',
    problem: 'barcode scanning is assumed to solve errors even though process timing and data discipline may be the root cause',
    problemAr: 'يُفترض أن مسح الباركود يحل الأخطاء رغم أن توقيت العملية وانضباط البيانات قد يكونان السبب الجذري',
    decision: 'test the receipt-delay hypothesis with observations and sample data before funding a solution',
    decisionAr: 'اختبار فرضية تأخر الإيصال بالملاحظات وعينات البيانات قبل تمويل حل',
    artifactFields: ['Problem statement', 'Target user', 'Assumption', 'Evidence needed', 'Experiment', 'Decision rule'],
    artifactFieldsAr: ['بيان المشكلة', 'المستخدم المستهدف', 'الافتراض', 'الأدلة المطلوبة', 'التجربة', 'قاعدة القرار'],
    artifactNameAr: 'موجز اكتشاف المنتج',
  },
  8: {
    topic: 'requirements',
    terms: ['requirement', 'epic', 'feature', 'user story', 'backlog item', 'traceability'],
    concepts: ['Requirements as needs', 'From outcome to hierarchy', 'Epics and features', 'User stories as slices', 'Non-functional needs', 'Business rules and constraints', 'Avoiding specification overload', 'Meridian backlog hierarchy'],
    conceptsAr: ['المتطلبات كاحتياجات', 'من النتيجة إلى التسلسل', 'الملحمات والميزات', 'قصص المستخدم كشرائح', 'الاحتياجات غير الوظيفية', 'قواعد العمل والقيود', 'تجنب فرط المواصفات', 'تسلسل قائمة مهام ميريديان'],
    outcome: 'turn sixty unstructured requests into traceable value-oriented work',
    outcomeAr: 'تحويل ستين طلبًا غير منظم إلى عمل قابل للتتبع وموجّه بالقيمة',
    problem: 'a shared spreadsheet mixes goals, defects, interface ideas, and detailed tasks',
    problemAr: 'جدول مشترك يخلط الأهداف والعيوب وأفكار الواجهة والمهام التفصيلية',
    decision: 'group requests by outcome and hierarchy before discussing Sprint selection',
    decisionAr: 'تجميع الطلبات حسب النتيجة والتسلسل قبل مناقشة اختيار السباق',
    artifactFields: ['Business outcome', 'Epic', 'Feature', 'Story', 'Constraint or rule', 'Open question'],
    artifactFieldsAr: ['نتيجة العمل', 'ملحمة', 'ميزة', 'قصة', 'قيد أو قاعدة', 'سؤال مفتوح'],
    artifactNameAr: 'تسلسل المتطلبات وقائمة المهام',
  },
  9: {
    topic: 'user_stories',
    terms: ['user story', 'persona', 'INVEST', 'benefit', 'vertical slice', 'conversation'],
    concepts: ['Stories are promises to converse', 'User role and need', 'Value statements', 'INVEST quality', 'Vertical slicing', 'Story mapping', 'Writing with Developers', 'Horizon story collection'],
    conceptsAr: ['القصص وعد بالحوار', 'دور المستخدم والحاجة', 'بيانات القيمة', 'جودة INVEST', 'التقطيع العمودي', 'خرائط القصص', 'الكتابة مع المطورين', 'مجموعة قصص Horizon'],
    outcome: 'give warehouse users small usable improvements instead of technical task lists',
    outcomeAr: 'منح مستخدمي المستودع تحسينات صغيرة قابلة للاستخدام بدل قوائم مهام تقنية',
    problem: 'stories such as “build API” and “make screen better” hide user value and cannot be prioritized well',
    problemAr: 'قصص مثل «ابنِ واجهة برمجة» و«حسّن الشاشة» تخفي قيمة المستخدم ولا يمكن ترتيبها جيدًا',
    decision: 'write a receiving story around an operator outcome and split it by workflow complexity',
    decisionAr: 'كتابة قصة استلام حول نتيجة المشغّل وتقسيمها حسب تعقيد سير العمل',
    artifactFields: ['Story title', 'As a', 'I want', 'So that', 'Acceptance conversation', 'Split rationale'],
    artifactFieldsAr: ['عنوان القصة', 'بصفتي', 'أريد', 'حتى', 'حوار القبول', 'مبرر التقسيم'],
    artifactNameAr: 'مجموعة قصص مستخدم احترافية',
  },
  10: {
    topic: 'acceptance_criteria',
    terms: ['acceptance criteria', 'business rule', 'Given When Then', 'example mapping', 'testability', 'ambiguity'],
    concepts: ['Why acceptance needs evidence', 'Criteria versus requirements', 'Given When Then examples', 'Business rules', 'Happy and exception paths', 'Example mapping conversations', 'Acceptance and Definition of Done', 'Meridian acceptance map'],
    conceptsAr: ['لماذا يحتاج القبول إلى أدلة', 'المعايير مقابل المتطلبات', 'أمثلة Given When Then', 'قواعد العمل', 'المسار السعيد ومسارات الاستثناء', 'حوارات خرائط الأمثلة', 'القبول وتعريف الإنجاز', 'خريطة قبول ميريديان'],
    outcome: 'ensure receipt posting is demonstrably correct and auditable',
    outcomeAr: 'ضمان أن ترحيل الإيصال صحيح وقابل للتدقيق بشكل واضح',
    problem: 'QA cannot determine whether a partially received purchase order is acceptable',
    problemAr: 'ضمان الجودة لا يستطيع تحديد ما إذا كان أمر شراء مستلم جزئيًا مقبولًا',
    decision: 'make valuation and late-posting rules explicit before development begins',
    decisionAr: 'جعل قواعد التقييم والترحيل المتأخر صريحة قبل بدء التطوير',
    artifactFields: ['Story', 'Rule', 'Given', 'When', 'Then', 'Examples', 'Open question'],
    artifactFieldsAr: ['قصة', 'قاعدة', 'بما أن', 'عندما', 'فإن', 'أمثلة', 'سؤال مفتوح'],
    artifactNameAr: 'معايير القبول وخريطة الأمثلة',
  },
  11: {
    topic: 'backlog_management',
    terms: ['Product Backlog', 'ordering', 'emergent', 'refinement', 'transparency', 'backlog item'],
    concepts: ['The Product Backlog as source of truth', 'Ordering versus a queue', 'Backlog item attributes', 'Keeping it emergent', 'Removing duplicates and stale work', 'Transparency and access', 'Backlog health measures', 'Meridian backlog build'],
    conceptsAr: ['قائمة مهام المنتج كمصدر حقيقة', 'الترتيب مقابل الطابور', 'خصائص عنصر القائمة', 'الإبقاء عليها ناشئة', 'إزالة التكرار والعمل القديم', 'الشفافية والوصول', 'مقاييس صحة القائمة', 'بناء قائمة ميريديان'],
    outcome: 'maintain one trusted decision surface for inventory work',
    outcomeAr: 'الحفاظ على سطح قرار موثوق واحد لعمل المخزون',
    problem: 'duplicate emailed requests and old ideas compete with current operational risks',
    problemAr: 'طلبات مكررة بالبريد وأفكار قديمة تتنافس مع المخاطر التشغيلية الحالية',
    decision: 'archive invalid items, merge duplicates, and order remaining work against the Product Goal',
    decisionAr: 'أرشفة العناصر غير الصالحة ودمج المكرر وترتيب الباقي وفق هدف المنتج',
    artifactFields: ['Backlog item', 'Outcome link', 'Order', 'Evidence', 'Status', 'Next refinement action'],
    artifactFieldsAr: ['عنصر القائمة', 'رابط النتيجة', 'الترتيب', 'الدليل', 'الحالة', 'إجراء التنقيح التالي'],
    artifactNameAr: 'قائمة مهام المنتج الكاملة',
  },
  12: {
    topic: 'prioritization',
    terms: ['prioritization', 'cost of delay', 'risk', 'value', 'WSJF', 'trade-off'],
    concepts: ['Prioritization is a decision', 'Value and urgency', 'Cost of delay', 'Risk reduction', 'Prioritization methods', 'Sequencing dependencies', 'Saying no and not now', 'Meridian priority rationale'],
    conceptsAr: ['تحديد الأولويات قرار', 'القيمة والإلحاح', 'تكلفة التأخير', 'تقليل المخاطر', 'أساليب الأولوية', 'تسلسل الاعتماديات', 'قول لا وليس الآن', 'منطق أولوية ميريديان'],
    outcome: 'choose the next work that most improves trusted availability',
    outcomeAr: 'اختيار العمل التالي الذي يحسّن التوافر الموثوق أكثر',
    problem: 'every department labels its own request urgent and asks for equal capacity',
    problemAr: 'كل قسم يصف طلبه بالعاجل ويطلب سعة متساوية',
    decision: 'prioritize receiving accuracy and availability evidence over a dashboard that merely reports bad data',
    decisionAr: 'إعطاء أولوية لدقة الاستلام وأدلة التوافر على لوحة تعرض بيانات سيئة فقط',
    artifactFields: ['Candidate', 'Value', 'Urgency', 'Risk', 'Effort signal', 'Order', 'Rationale'],
    artifactFieldsAr: ['مرشح', 'القيمة', 'الإلحاح', 'المخاطر', 'إشارة الجهد', 'الترتيب', 'المبرر'],
    artifactNameAr: 'قائمة مرتبة بمنطق القرار',
  },
  13: {
    topic: 'estimation_forecasting',
    terms: ['estimate', 'forecast', 'capacity', 'velocity', 'range', 'uncertainty'],
    concepts: ['Estimates are not promises', 'Relative estimation', 'Capacity and availability', 'Velocity as history', 'Forecast ranges', 'Dependencies and risk', 'Communicating uncertainty', 'Meridian release forecast'],
    conceptsAr: ['التقديرات ليست وعودًا', 'التقدير النسبي', 'السعة والتوافر', 'السرعة كتاريخ', 'نطاقات التنبؤ', 'الاعتماديات والمخاطر', 'إيصال عدم اليقين', 'تنبؤ إصدار ميريديان'],
    outcome: 'offer leadership a credible delivery range for foundational inventory capability',
    outcomeAr: 'تقديم نطاق تسليم موثوق للقيادة لقدرة المخزون الأساسية',
    problem: 'leadership wants an exact release date from early estimates and changing scope',
    problemAr: 'القيادة تريد تاريخ إصدار دقيق من تقديرات مبكرة ونطاق متغير',
    decision: 'forecast a range based on capacity and assumptions, and state the conditions that change it',
    decisionAr: 'التنبؤ بنطاق بناءً على السعة والافتراضات وبيان الشروط التي تغيّره',
    artifactFields: ['Scope hypothesis', 'Capacity', 'Estimate range', 'Assumptions', 'Risk', 'Forecast range', 'Review date'],
    artifactFieldsAr: ['فرضية النطاق', 'السعة', 'نطاق التقدير', 'الافتراضات', 'المخاطر', 'نطاق التنبؤ', 'تاريخ المراجعة'],
    artifactNameAr: 'قائمة مقدّرة وتنبؤ',
  },
  14: {
    topic: 'refinement',
    terms: ['refinement', 'Definition of Ready', 'slicing', 'clarity', 'estimate', 'dependency'],
    concepts: ['Refinement purpose', 'Readiness versus certainty', 'Collaborative clarification', 'Splitting oversized work', 'Finding dependencies', 'Estimating at the right time', 'Definition of Ready signals', 'Meridian refinement session'],
    conceptsAr: ['غرض التنقيح', 'الجاهزية مقابل اليقين', 'التوضيح التعاوني', 'تقسيم العمل الكبير', 'اكتشاف الاعتماديات', 'التقدير في الوقت المناسب', 'إشارات تعريف الجاهزية', 'جلسة تنقيح ميريديان'],
    outcome: 'make the next Sprint candidates understandable, valuable, and small enough to plan',
    outcomeAr: 'جعل مرشحي السباق التالي مفهومين وذوي قيمة وصغارًا بما يكفي للتخطيط',
    problem: 'selected items lack examples, dependencies, and shared understanding',
    problemAr: 'العناصر المختارة تفتقر للأمثلة والاعتماديات والفهم المشترك',
    decision: 'return unclear work to refinement rather than carry ambiguity into Sprint Planning',
    decisionAr: 'إعادة العمل غير الواضح للتنقيح بدل حمل الغموض إلى تخطيط السباق',
    artifactFields: ['Item', 'Value', 'Examples', 'Size signal', 'Dependency', 'Risk', 'Ready decision'],
    artifactFieldsAr: ['عنصر', 'القيمة', 'أمثلة', 'إشارة الحجم', 'اعتمادية', 'مخاطر', 'قرار الجاهزية'],
    artifactNameAr: 'قائمة جاهزة للسباق',
  },
  15: {
    topic: 'sprint_planning',
    terms: ['Sprint Planning', 'Sprint Goal', 'capacity', 'forecast', 'Sprint Backlog', 'trade-off'],
    concepts: ['Sprint Planning purpose', 'A coherent Sprint Goal', 'Why before what', 'Capacity-aware selection', 'Developer forecast', 'Negotiating scope', 'Creating a Sprint Backlog', 'Meridian Sprint plan'],
    conceptsAr: ['غرض تخطيط السباق', 'هدف سباق متماسك', 'لماذا قبل ماذا', 'اختيار واعٍ بالسعة', 'تنبؤ المطورين', 'التفاوض على النطاق', 'إنشاء قائمة مهام السباق', 'خطة سباق ميريديان'],
    outcome: 'deliver a coherent receipt-to-availability slice within actual team capacity',
    outcomeAr: 'تسليم شريحة متماسكة من الإيصال إلى التوافر ضمن سعة الفريق الفعلية',
    problem: 'stakeholders want five unrelated requests inserted into a Sprint with limited capacity',
    problemAr: 'أصحاب المصلحة يريدون إدراج خمسة طلبات غير مرتبطة في سباق بسعة محدودة',
    decision: 'select work that serves one Sprint Goal and transparently defer unrelated requests',
    decisionAr: 'اختيار عمل يخدم هدف سباق واحد وتأجيل الطلبات غير المرتبطة بشفافية',
    artifactFields: ['Sprint Goal', 'Selected items', 'Capacity assumptions', 'Expected value', 'Excluded items', 'Risk', 'Review evidence'],
    artifactFieldsAr: ['هدف السباق', 'العناصر المختارة', 'افتراضات السعة', 'القيمة المتوقعة', 'العناصر المستبعدة', 'المخاطر', 'أدلة المراجعة'],
    artifactNameAr: 'هدف السباق وخطة السباق',
  },
  16: {
    topic: 'sprint_execution',
    terms: ['Sprint Goal', 'Daily Scrum', 'scope negotiation', 'impediment', 'replanning', 'decision log'],
    concepts: ['PO availability during Sprint', 'Protecting the Sprint Goal', 'Clarification without micromanagement', 'Mid-Sprint change', 'Urgent defects', 'Daily collaboration', 'Decision logging', 'Meridian execution choices'],
    conceptsAr: ['توفر مالك المنتج أثناء السباق', 'حماية هدف السباق', 'التوضيح دون إدارة دقيقة', 'تغيير منتصف السباق', 'عيوب عاجلة', 'التعاون اليومي', 'تسجيل القرارات', 'اختيارات تنفيذ ميريديان'],
    outcome: 'keep the team focused while resolving a real receiving defect quickly',
    outcomeAr: 'إبقاء الفريق مركّزًا مع حل عيب استلام حقيقي بسرعة',
    problem: 'Customer Service requests a new screen while a receiving bug threatens the Sprint Goal',
    problemAr: 'خدمة العملاء تطلب شاشة جديدة بينما عيب استلام يهدد هدف السباق',
    decision: 'triage the defect against impact, defer the screen request, and make the trade-off visible',
    decisionAr: 'فرز العيب حسب التأثير وتأجيل طلب الشاشة وإظهار المقايضة',
    artifactFields: ['Date', 'Request or issue', 'Sprint Goal impact', 'Evidence', 'Decision', 'Owner', 'Follow-up'],
    artifactFieldsAr: ['التاريخ', 'الطلب أو المشكلة', 'أثر هدف السباق', 'الدليل', 'القرار', 'المالك', 'المتابعة'],
    artifactNameAr: 'سجل قرارات مالك المنتج',
  },
  17: {
    topic: 'quality_acceptance',
    terms: ['quality', 'acceptance', 'Definition of Done', 'UAT', 'evidence', 'defect'],
    concepts: ['Quality is built in', 'Acceptance versus approval', 'Definition of Done', 'Acceptance Criteria evidence', 'UAT roles', 'Defects and trade-offs', 'Auditability and ERP quality', 'Meridian acceptance report'],
    conceptsAr: ['الجودة تُبنى داخليًا', 'القبول مقابل الموافقة', 'تعريف الإنجاز', 'أدلة معايير القبول', 'أدوار اختبار القبول', 'العيوب والمقايضات', 'قابلية التدقيق وجودة ERP', 'تقرير قبول ميريديان'],
    outcome: 'accept only usable, auditable receipt functionality that meets critical rules',
    outcomeAr: 'قبول وظائف إيصال قابلة للاستخدام والتدقيق فقط وتلبي القواعد الحرجة',
    problem: 'a demonstration looks complete but permits a stock movement without the required finance audit trail',
    problemAr: 'عرض يبدو مكتملًا لكنه يسمح بحركة مخزون دون مسار تدقيق مالي مطلوب',
    decision: 'reject the affected backlog item until the critical rule has evidence of passing',
    decisionAr: 'رفض عنصر القائمة المتأثر حتى تتوفر أدلة على اجتياز القاعدة الحرجة',
    artifactFields: ['Increment', 'Criteria', 'Evidence', 'Pass or fail', 'Defect severity', 'Acceptance decision', 'Follow-up'],
    artifactFieldsAr: ['الزيادة', 'المعايير', 'الدليل', 'نجاح أو فشل', 'خطورة العيب', 'قرار القبول', 'المتابعة'],
    artifactNameAr: 'تقرير اختبار القبول وقبول المنتج',
  },
  18: {
    topic: 'review_retrospective',
    terms: ['Sprint Review', 'retrospective', 'feedback', 'adaptation', 'action', 'inspection'],
    concepts: ['Review and retrospective differ', 'Inspecting the Increment', 'Inviting useful feedback', 'Outcome evidence', 'Retrospective safety', 'Improvement experiments', 'Adapting backlog and process', 'Meridian improvement report'],
    conceptsAr: ['المراجعة والاستعراض يختلفان', 'فحص الزيادة', 'دعوة تغذية راجعة مفيدة', 'أدلة النتيجة', 'أمان الاستعراض', 'تجارب التحسين', 'تكييف القائمة والعملية', 'تقرير تحسين ميريديان'],
    outcome: 'use live warehouse feedback to adapt both backlog order and refinement practice',
    outcomeAr: 'استخدام تغذية راجعة حية من المستودع لتكييف ترتيب القائمة وممارسة التنقيح',
    problem: 'review attendees request conflicting changes while the team repeats vague-story rework',
    problemAr: 'حضور المراجعة يطلبون تغييرات متعارضة بينما يكرر الفريق إعادة عمل القصص الغامضة',
    decision: 'separate product feedback from process improvement, then create owned experiments for both',
    decisionAr: 'فصل تغذية المنتج عن تحسين العملية ثم إنشاء تجارب مملوكة لكليهما',
    artifactFields: ['Observed outcome', 'Feedback', 'Backlog adaptation', 'Process insight', 'Experiment', 'Owner', 'Review date'],
    artifactFieldsAr: ['النتيجة الملاحظة', 'التغذية الراجعة', 'تكييف القائمة', 'رؤية العملية', 'التجربة', 'المالك', 'تاريخ المراجعة'],
    artifactNameAr: 'تقرير مراجعة السباق والتحسين',
  },
  19: {
    topic: 'roadmaps_metrics',
    terms: ['roadmap', 'release', 'MVP', 'metric', 'leading indicator', 'outcome'],
    concepts: ['Roadmaps communicate direction', 'Outcome-based roadmap themes', 'Release planning', 'MVP and MMP', 'Product metrics', 'Leading and lagging measures', 'Metric ethics and trade-offs', 'Meridian roadmap framework'],
    conceptsAr: ['خرائط الطريق توصل الاتجاه', 'موضوعات خارطة مبنية على النتائج', 'تخطيط الإصدار', 'MVP و MMP', 'مقاييس المنتج', 'مؤشرات رائدة ومتأخرة', 'أخلاقيات المقاييس والمقايضات', 'إطار خارطة ميريديان'],
    outcome: 'communicate a credible path from receipt accuracy to reliable customer promises',
    outcomeAr: 'إيصال مسار موثوق من دقة الإيصال إلى وعود العملاء الموثوقة',
    problem: 'leadership asks for a date-heavy roadmap with no outcome measures or learning checkpoints',
    problemAr: 'القيادة تطلب خارطة مثقلة بالتواريخ بلا مقاييس نتائج أو نقاط تعلم',
    decision: 'publish theme-based horizons with release hypotheses and metrics rather than fixed feature promises',
    decisionAr: 'نشر آفاق مبنية على موضوعات مع فرضيات إصدار ومقاييس بدل وعود ميزات ثابتة',
    artifactFields: ['Horizon', 'Outcome', 'Theme', 'Release hypothesis', 'Metric', 'Assumption', 'Review trigger'],
    artifactFieldsAr: ['الأفق', 'النتيجة', 'الموضوع', 'فرضية الإصدار', 'المقياس', 'الافتراض', 'محفز المراجعة'],
    artifactNameAr: 'خارطة الطريق وخطة الإصدار وإطار المقاييس',
  },
  20: {
    topic: 'professional_practice',
    terms: ['product strategy', 'discovery', 'backlog', 'stakeholder management', 'evidence', 'professional judgment'],
    concepts: ['End-to-end Product Ownership', 'Diagnosing an unclear request', 'Strategy and discovery integration', 'Backlog and prioritization choices', 'Sprint and acceptance leadership', 'Stakeholder communication', 'Metrics and adaptation', 'Professional simulation debrief'],
    conceptsAr: ['ملكية منتج من البداية للنهاية', 'تشخيص طلب غير واضح', 'دمج الاستراتيجية والاكتشاف', 'اختيارات القائمة والأولوية', 'قيادة السباق والقبول', 'تواصل أصحاب المصلحة', 'المقاييس والتكييف', 'تقييم المحاكاة المهنية'],
    outcome: 'make a defensible end-to-end decision about AI warehouse planning',
    outcomeAr: 'اتخاذ قرار شامل قابل للدفاع حول تخطيط المستودع بالذكاء الاصطناعي',
    problem: 'a sponsor asks for AI without a defined user problem, evidence, outcome, or delivery trade-off',
    problemAr: 'راعٍ يطلب ذكاءً اصطناعيًا دون مشكلة مستخدم محددة أو أدلة أو نتيجة أو مقايضة تسليم',
    decision: 'treat AI as a hypothesis, run discovery, and protect foundational inventory work until evidence justifies change',
    decisionAr: 'معاملة الذكاء الاصطناعي كفرضية وتشغيل الاكتشاف وحماية عمل المخزون الأساسي حتى تبرر الأدلة التغيير',
    artifactFields: ['Request', 'Problem hypothesis', 'Evidence plan', 'Product Goal link', 'Backlog decision', 'Stakeholder message', 'Success metric'],
    artifactFieldsAr: ['الطلب', 'فرضية المشكلة', 'خطة الأدلة', 'رابط هدف المنتج', 'قرار القائمة', 'رسالة أصحاب المصلحة', 'مقياس النجاح'],
    artifactNameAr: 'محفظة مالك منتج احترافية',
  },
};

const QUIZ_OPTS_EN = [
  'Commit to the first executive request without evidence',
  'Use evidence and the Product Goal to make and communicate a trade-off',
  'Ask every department to maintain a separate priority list',
  'Wait for a complete fixed specification before learning',
] as const;
const QUIZ_OPTS_AR = [
  'الالتزام بأول طلب تنفيذي دون أدلة',
  'استخدام الأدلة وهدف المنتج لاتخاذ مقايضة وإيصالها',
  'طلب أن يحافظ كل قسم على قائمة أولويات منفصلة',
  'انتظار مواصفة ثابتة كاملة قبل التعلم',
] as const;
const QUIZ_CORRECT = QUIZ_OPTS_EN[1];
const QUIZ_CORRECT_AR = QUIZ_OPTS_AR[1];

const EXAM_OPTS_EN = [
  'Commit immediately to avoid conflict',
  'Clarify the problem, compare it to the Product Goal and evidence, order it transparently, and communicate the trade-off',
  'Ask Developers to decide product priority alone',
  'Ignore the stakeholder request',
] as const;
const EXAM_OPTS_AR = [
  'الالتزام فورًا لتجنب التعارض',
  'توضيح المشكلة ومقارنتها بهدف المنتج والأدلة وترتيبها بشفافية وإيصال المقايضة',
  'طلب أن يقرر المطورون أولوية المنتج وحدهم',
  'تجاهل طلب صاحب المصلحة',
] as const;
const EXAM_CORRECT = EXAM_OPTS_EN[1];
const EXAM_CORRECT_AR = EXAM_OPTS_AR[1];

export function createFullDay(dayNumber: number): DayCurriculum {
  const summary = DAY_SUMMARIES.find((item) => item.dayNumber === dayNumber);
  const detail = DETAILS[dayNumber];
  if (!summary || !detail) throw new Error(`No full curriculum configured for day ${dayNumber}`);
  const topic = detail.topic;
  const narrative = caseStudyDayNarrative(dayNumber);
  const narrativeAr = caseStudyDayNarrativeAr(dayNumber);

  const sections = detail.concepts.map((concept, index) => {
    const conceptAr = detail.conceptsAr[index];
    return deepConcept({
      id: `d${dayNumber}-s${index + 1}`,
      title: concept,
      titleAr: conceptAr,
      type: index === 3 ? 'process' : index === 5 ? 'worked_example' : 'theory',
      content: {
        conceptIntroduction: `${concept} is a distinct Product Owner capability within ${summary.title}. It gives you a way to make a deliberate decision instead of reacting to the loudest request.`,
        simpleExplanation: `In plain language, use ${concept.toLowerCase()} to help Meridian learn what improves the product, then make the next choice visible.`,
        businessProblem: `Meridian needs to ${detail.outcome}. Today, ${detail.problem}.`,
        professionalDefinition: `${concept} is applied deliberately: the Product Owner gathers relevant evidence, makes the value trade-off explicit, and aligns the Product Backlog or team conversation with the Product Goal.`,
        whyImportant: `Without this practice, Horizon ERP risks delivering activity rather than value and stakeholders cannot understand why work is ordered.`,
        lifecycleLocation: `It is used before delivery to shape decisions, during delivery to clarify trade-offs, and after delivery to inspect whether ${detail.outcome}.`,
        howItWorks: `1) State the decision. 2) Identify users and evidence. 3) Connect the decision to the Product Goal. 4) Compare alternatives and constraints. 5) Communicate the decision and inspect its result.`,
        whoResponsible: 'The Product Owner owns the product-value decision. Developers, users, and specialists contribute evidence and options.',
        whoParticipates: 'Warehouse operators, Inventory Control, Customer Service, Finance, Developers, and the Scrum Master participate according to the question.',
        requiredInputs: 'Product Goal, user evidence, operational data, constraints, stakeholder input, and the current ordered Product Backlog.',
        activities: `Analyze the current situation, discuss ${concept.toLowerCase()} with collaborators, make a visible decision, and update the relevant product artifact.`,
        expectedOutputs: `${summary.artifactName}, a clearer Product Backlog decision, and a shared explanation of how the choice supports ${detail.outcome}.`,
        simpleExample: `A shop owner observes that customers leave because the queue is slow, tests a simpler checkout step, and keeps it only if waiting time falls.`,
        softwareExample: 'A team releases a small workflow, observes completion and support signals, then improves the highest-friction step instead of building every requested option.',
        erpExample: `${CASE_STUDY.productName} Inventory & Warehouse uses ${concept.toLowerCase()} to improve late receipt handling, stock truth, and customer promise reliability at ${CASE_STUDY.companyName}.`,
        workedExample: `Meridian situation: ${detail.problem}\nPO decision: ${detail.decision}.\nEvidence to inspect: receipt timestamps, cycle-count variance, and operator feedback.\nExpected learning: whether the selected action advances ${detail.outcome}.`,
        comparison: `A professional Product Owner distinguishes evidence from opinion, an outcome from an output, and a decision from an unexamined request when applying ${concept.toLowerCase()}.`,
        commonMisunderstandings: `Misunderstanding: ${concept} means completing a document or meeting. Correction: it is valuable only when it changes a product decision using evidence.`,
        beginnerMistakes: [
          { wrong: 'Treating the first suggested solution as the requirement', right: 'State the user problem and desired outcome before selecting a solution', explanation: 'This preserves options and prevents expensive rework.' },
          { wrong: 'Recording a decision without the reason', right: 'Capture evidence, trade-off, and review point', explanation: 'Stakeholders can then challenge assumptions productively.' },
        ],
        workplaceMistakes: [
          { wrong: 'Allowing each department to maintain its own priority list', right: 'Use one transparent Product Backlog and communicate the ordering rationale', explanation: 'Competing hidden lists destroy focus and trust.' },
        ],
        poorExample: `“${concept} is urgent, so build it now.”`,
        correctExample: `“We will ${detail.decision} because it best supports ${detail.outcome}; we will inspect the agreed evidence at the next Sprint Review.”`,
        guidedPractice: `Use the Meridian narrative to identify the evidence required before applying ${concept.toLowerCase()}.`,
        independentPractice: `Write and defend a Product Owner decision that applies ${concept.toLowerCase()} to one Horizon ERP backlog item.`,
        scenarioDecision: `Finance requests more controls while Warehouse requests speed. Use ${concept.toLowerCase()} to make the trade-off transparent rather than promising both immediately.`,
        reflectionQuestion: `What evidence would make you change your Meridian decision about ${concept.toLowerCase()}?`,
        professionalTerminology: `Use “evidence,” “outcome,” “Product Goal,” “trade-off,” and the topic terms precisely; avoid calling every stakeholder request a commitment.`,
        interviewQuestion: `How would you apply ${concept.toLowerCase()} as Product Owner for an ERP product?`,
        interviewModelAnswer: `I would begin with the operational problem and target outcome, involve the people who hold evidence, and make the Product Backlog decision transparent. For Meridian, I would ${detail.decision}, inspect the result, and adapt rather than treat the initial request as a fixed commitment.`,
        comparisonTable: index === 0 ? table(
          `${summary.title}: decision comparison`,
          ['Approach', 'What happens', 'Product Owner risk', 'Better practice'],
          [
            ['React to the loudest request', 'Busy Sprint, unclear value', 'Shadow priorities and rework', 'Order by Product Goal evidence'],
            ['Freeze a full solution early', 'Delayed learning', 'Wrong solution at high cost', 'Inspect a thin Increment first'],
            ['Document without deciding', 'Meetings without trade-offs', 'No one owns the outcome', 'Decide, communicate, review'],
            [detail.decision, `Advances ${detail.outcome}`, 'Managed if evidence is inspected', 'Keep the decision transparent'],
          ],
        ) : undefined,
        processSteps: index === 3 ? steps(
          { id: `d${dayNumber}-p1`, label: 'Frame the decision', description: `State the Meridian problem: ${detail.problem}` },
          { id: `d${dayNumber}-p2`, label: 'Gather evidence', description: 'Collect user observation, operational data, and stakeholder constraints.' },
          { id: `d${dayNumber}-p3`, label: 'Compare options', description: 'Evaluate alternatives against the Product Goal and risks.' },
          { id: `d${dayNumber}-p4`, label: 'Decide and communicate', description: detail.decision },
          { id: `d${dayNumber}-p5`, label: 'Inspect and adapt', description: `Review whether work advances ${detail.outcome}.` },
        ) : undefined,
        ar: {
          conceptIntroduction: `${conceptAr} قدرة مميزة لمالك المنتج ضمن ${summary.titleAr}. تمنحك طريقة لاتخاذ قرار متعمد بدل الاستجابة لأعلى صوت.`,
          simpleExplanation: `بلغة بسيطة، استخدم «${conceptAr}» لمساعدة ميريديان على تعلم ما يحسّن المنتج، ثم اجعل الاختيار التالي مرئيًا.`,
          businessProblem: `تحتاج ميريديان إلى ${detail.outcomeAr}. اليوم، ${detail.problemAr}.`,
          professionalDefinition: `يُطبَّق «${conceptAr}» عمدًا: يجمع مالك المنتج الأدلة ذات الصلة، ويُظهر مقايضة القيمة، ويوائم قائمة مهام المنتج أو حوار الفريق مع هدف المنتج.`,
          whyImportant: 'بدون هذه الممارسة، يخاطر Horizon ERP بتسليم نشاط لا قيمة، ولا يفهم أصحاب المصلحة لماذا يُرتَّب العمل.',
          lifecycleLocation: `يُستخدم قبل التسليم لتشكيل القرارات، وأثناء التسليم لتوضيح المقايضات، وبعد التسليم لفحص ما إذا تحقق ${detail.outcomeAr}.`,
          howItWorks: '1) صِغ القرار. 2) حدّد المستخدمين والأدلة. 3) اربط القرار بهدف المنتج. 4) قارن البدائل والقيود. 5) أوصل القرار وافحص نتيجته.',
          whoResponsible: 'يملك مالك المنتج قرار قيمة المنتج. يساهم المطورون والمستخدمون والمتخصصون بالأدلة والخيارات.',
          whoParticipates: 'يشارك مشغّلو المستودع ومراقبة المخزون وخدمة العملاء والمالية والمطورون وسكرم ماستر حسب السؤال.',
          requiredInputs: 'هدف المنتج، أدلة المستخدمين، البيانات التشغيلية، القيود، مدخلات أصحاب المصلحة، وقائمة مهام المنتج المرتبة الحالية.',
          activities: `حلّل الوضع الحالي، ناقش «${conceptAr}» مع المتعاونين، اتخذ قرارًا مرئيًا، وحدّث مخرج المنتج ذي الصلة.`,
          expectedOutputs: `${detail.artifactNameAr}، وقرار أوضح في قائمة مهام المنتج، وشرح مشترك لكيف يدعم الاختيار ${detail.outcomeAr}.`,
          simpleExample: 'صاحب متجر يلاحظ مغادرة العملاء بسبب بطء الطابور، يختبر خطوة دفع أبسط، ويبقيها فقط إذا انخفض وقت الانتظار.',
          softwareExample: 'فريق يُصدر سير عمل صغيرًا، يراقب إشارات الإكمال والدعم، ثم يحسّن أعلى خطوة احتكاك بدل بناء كل خيار مطلوب.',
          erpExample: `يستخدم ${CASE_STUDY.productName} للمخزون والمستودع «${conceptAr}» لتحسين معالجة الإيصالات المتأخرة وحقيقة المخزون وموثوقية وعود العملاء في ${CASE_STUDY.companyName}.`,
          workedExample: `وضع ميريديان: ${detail.problemAr}\nقرار مالك المنتج: ${detail.decisionAr}.\nأدلة للفحص: طوابع وقت الإيصال، تباين الجرد الدوري، وتغذية راجعة من المشغّلين.\nالتعلم المتوقع: ما إذا كان الإجراء المختار يقدّم ${detail.outcomeAr}.`,
          comparison: `يميّز مالك المنتج المحترف الدليل عن الرأي، والنتيجة عن المخرج، والقرار عن الطلب غير المفحوص عند تطبيق «${conceptAr}».`,
          commonMisunderstandings: `سوء فهم: «${conceptAr}» يعني إكمال مستند أو اجتماع. التصحيح: قيمته تظهر فقط عندما يغيّر قرار منتج باستخدام الأدلة.`,
          beginnerMistakes: [
            { wrong: 'معاملة أول حل مقترح كمتطلب', right: 'صِغ مشكلة المستخدم والنتيجة المرغوبة قبل اختيار الحل', explanation: 'هذا يحافظ على الخيارات ويمنع إعادة العمل المكلفة.' },
            { wrong: 'تسجيل قرار دون السبب', right: 'التقط الدليل والمقايضة ونقطة المراجعة', explanation: 'يمكن لأصحاب المصلحة حينها تحدي الافتراضات بشكل منتج.' },
          ],
          workplaceMistakes: [
            { wrong: 'السماح لكل قسم بالاحتفاظ بقائمة أولويات خاصة', right: 'استخدم قائمة مهام منتج شفافة واحدة وأوصل منطق الترتيب', explanation: 'القوائم المخفية المتنافسة تدمر التركيز والثقة.' },
          ],
          poorExample: `«${conceptAr} عاجل، فابنِه الآن.»`,
          correctExample: `«سنقوم بـ ${detail.decisionAr} لأنه يدعم أفضل ${detail.outcomeAr}؛ وسنفحص الأدلة المتفق عليها في مراجعة السباق التالية.»`,
          guidedPractice: `استخدم سرد ميريديان لتحديد الأدلة المطلوبة قبل تطبيق «${conceptAr}».`,
          independentPractice: `اكتب وادافع عن قرار مالك منتج يطبّق «${conceptAr}» على عنصر واحد في قائمة Horizon ERP.`,
          scenarioDecision: `تطلب المالية ضوابط أكثر بينما يطلب المستودع السرعة. استخدم «${conceptAr}» لجعل المقايضة شفافة بدل وعد الاثنين فورًا.`,
          reflectionQuestion: `أي أدلة ستجعلك تغيّر قرارك في ميريديان بشأن «${conceptAr}»؟`,
          professionalTerminology: 'استخدم «أدلة» و«نتيجة» و«هدف المنتج» و«مقايضة» ومصطلحات الموضوع بدقة؛ تجنب اعتبار كل طلب من أصحاب المصلحة التزامًا.',
          interviewQuestion: `كيف تطبّق «${conceptAr}» كمالك منتج لمنتج ERP؟`,
          interviewModelAnswer: `سأبدأ بالمشكلة التشغيلية والنتيجة المستهدفة، وأشرك من يملكون الأدلة، وأجعل قرار قائمة المهام شفافًا. في ميريديان، سأقوم بـ ${detail.decisionAr}، وأفحص النتيجة، وأتكيّف بدل معاملة الطلب الأولي كالتزام ثابت.`,
          comparisonTable: index === 0 ? table(
            `${summary.titleAr}: مقارنة القرارات`,
            ['النهج', 'ما يحدث', 'مخاطر مالك المنتج', 'ممارسة أفضل'],
            [
              ['الرد على أعلى صوت', 'سباق مشغول وقيمة غير واضحة', 'أولويات ظل وإعادة عمل', 'الترتيب بأدلة هدف المنتج'],
              ['تجميد حل كامل مبكرًا', 'تأخير التعلم', 'حل خاطئ بتكلفة عالية', 'افحص زيادة رفيعة أولًا'],
              ['توثيق دون قرار', 'اجتماعات بلا مقايضات', 'لا أحد يملك النتيجة', 'قرّر وأوصل وراجع'],
              [detail.decisionAr, `يقدّم ${detail.outcomeAr}`, 'مُدار إذا فُحصت الأدلة', 'أبقِ القرار شفافًا'],
            ],
          ) : undefined,
          processSteps: index === 3 ? steps(
            { id: `d${dayNumber}-p1-ar`, label: 'صياغة القرار', description: `صِغ مشكلة ميريديان: ${detail.problemAr}` },
            { id: `d${dayNumber}-p2-ar`, label: 'جمع الأدلة', description: 'اجمع ملاحظة المستخدم والبيانات التشغيلية وقيود أصحاب المصلحة.' },
            { id: `d${dayNumber}-p3-ar`, label: 'مقارنة الخيارات', description: 'قيّم البدائل مقابل هدف المنتج والمخاطر.' },
            { id: `d${dayNumber}-p4-ar`, label: 'القرار والتواصل', description: detail.decisionAr },
            { id: `d${dayNumber}-p5-ar`, label: 'الفحص والتكييف', description: `راجع ما إذا كان العمل يقدّم ${detail.outcomeAr}.` },
          ) : undefined,
        },
      },
      requiresAnswer: prompt(
        `Apply ${concept} to Meridian in 4–6 sentences. Name a user, evidence, a Product Owner decision, and the outcome you will inspect.`,
        'write',
        `For Meridian, I would use ${concept.toLowerCase()} with Warehouse and Customer Service evidence. I would ${detail.decision}. This supports ${detail.outcome}; I would inspect receipt timing, inventory accuracy, and user feedback before expanding scope.`,
        'Use user, evidence, decision, and outcome',
        ['Meridian', 'evidence', 'decision', 'outcome'],
        {
          question: `طبّق «${conceptAr}» على ميريديان في 4–6 جمل. اذكر مستخدمًا ودليلًا وقرار مالك منتج والنتيجة التي ستفحصها.`,
          modelAnswer: `في ميريديان، سأستخدم «${conceptAr}» مع أدلة المستودع وخدمة العملاء. سأقوم بـ ${detail.decisionAr}. هذا يدعم ${detail.outcomeAr}؛ وسأفحص توقيت الإيصال ودقة المخزون وتغذية راجعة المستخدمين قبل توسيع النطاق.`,
          hint: 'استخدم مستخدمًا ودليلًا وقرارًا ونتيجة',
        },
      ),
    });
  });

  const quiz = detail.concepts.map((concept, index) => mcq(
    `d${dayNumber}-q${index + 1}`, topic,
    `Which Product Owner action best demonstrates ${concept.toLowerCase()} at Meridian?`,
    [...QUIZ_OPTS_EN],
    QUIZ_CORRECT,
    `${concept} requires an evidence-based product decision. It does not mean automatic commitment, fragmented ordering, or delaying learning until certainty exists.`,
    10,
    {
      question: `أي إجراء لمالك المنتج يُظهر أفضل «${detail.conceptsAr[index]}» في ميريديان؟`,
      options: [...QUIZ_OPTS_AR],
      correctAnswer: QUIZ_CORRECT_AR,
      explanation: `يتطلب «${detail.conceptsAr[index]}» قرار منتج قائم على الأدلة. لا يعني التزامًا تلقائيًا أو ترتيبًا مجزأ أو تأجيل التعلم حتى يوجد يقين.`,
    },
  ));
  quiz.push(mcq(
    `d${dayNumber}-q9`, topic,
    `What should the Product Owner inspect after applying ${summary.title}?`,
    ['Whether every stakeholder is equally happy', 'Outcome evidence related to the Product Goal', 'Only whether the document was completed', 'Only individual developer utilization'],
    'Outcome evidence related to the Product Goal',
    'Product work is judged by value and learning, not document completion or local utilization.',
    10,
    {
      question: `ماذا يجب أن يفحص مالك المنتج بعد تطبيق ${summary.titleAr}؟`,
      options: ['ما إذا كان كل أصحاب المصلحة سعداء بالتساوي', 'أدلة النتيجة المرتبطة بهدف المنتج', 'فقط ما إذا اكتمل المستند', 'فقط استخدام المطور الفردي'],
      correctAnswer: 'أدلة النتيجة المرتبطة بهدف المنتج',
      explanation: 'يُحكم على عمل المنتج بالقيمة والتعلم، لا باكتمال المستند أو الاستخدام المحلي.',
    },
  ));
  quiz.push(mcq(
    `d${dayNumber}-q10`, topic,
    'When stakeholders conflict, what is the strongest response?',
    ['Promise all requests this Sprint', 'Explain an evidence-based order and review point', 'Let the loudest person decide', 'Hide the decision until release'],
    'Explain an evidence-based order and review point',
    'Transparent rationale preserves relationships while protecting product focus.',
    10,
    {
      question: 'عند تعارض أصحاب المصلحة، ما أقوى استجابة؟',
      options: ['وعد بكل الطلبات في هذا السباق', 'شرح ترتيب قائم على الأدلة ونقطة مراجعة', 'ترك أعلى صوت يقرر', 'إخفاء القرار حتى الإصدار'],
      correctAnswer: 'شرح ترتيب قائم على الأدلة ونقطة مراجعة',
      explanation: 'المنطق الشفاف يحافظ على العلاقات ويحمي تركيز المنتج.',
    },
  ));

  const exam = Array.from({ length: 5 }, (_, index) => scenarioQ(
    `d${dayNumber}-e${index + 1}`, topic,
    `Scenario ${index + 1}: ${narrative} A senior stakeholder demands an immediate solution that conflicts with current evidence. What should you do?`,
    [...EXAM_OPTS_EN],
    EXAM_CORRECT,
    `A capable Product Owner respects the request without confusing it with a commitment. The right response protects ${detail.outcome} through evidence and transparent ordering.`,
    20,
    {
      question: `سيناريو ${index + 1}: ${narrativeAr} يطلب صاحب مصلحة كبير حلًا فوريًا يتعارض مع الأدلة الحالية. ماذا تفعل؟`,
      options: [...EXAM_OPTS_AR],
      correctAnswer: EXAM_CORRECT_AR,
      explanation: `يحترم مالك المنتج القادر الطلب دون خلطه بالتزام. الاستجابة الصحيحة تحمي ${detail.outcomeAr} عبر الأدلة والترتيب الشفاف.`,
    },
  ));

  return {
    dayNumber, title: summary.title, titleAr: summary.titleAr, subtitle: summary.subtitle, subtitleAr: summary.subtitleAr,
    difficulty: summary.difficulty, estimatedHours: summary.estimatedHours,
    prerequisites: [`Complete Day ${dayNumber - 1} and review its artifact`, 'Bring the Meridian case study notes forward'],
    prerequisitesAr: [`أكمل اليوم ${dayNumber - 1} وراجع مخرجه`, 'انقل ملاحظات دراسة حالة ميريديان معك'],
    topics: [topic],
    objectives: [`Explain and apply ${summary.title}`, `Make an evidence-based Product Owner decision for Horizon ERP`, `Produce a ${summary.artifactName}`, 'Handle stakeholder conflict with a transparent rationale', 'Pass a topic-specific quiz and scenario exam'],
    objectivesAr: [`شرح وتطبيق ${summary.titleAr}`, 'اتخاذ قرار مالك منتج قائم على الأدلة لـ Horizon ERP', `إنتاج ${detail.artifactNameAr}`, 'إدارة تعارض أصحاب المصلحة بمنطق واضح', 'اجتياز الاختبار والامتحان القائم على السيناريو'],
    keyTerminology: detail.terms,
    sections,
    productOwnerResponsibility: ['Own Product Backlog ordering', 'Maximize value toward the Product Goal', 'Make trade-offs transparent', 'Seek evidence from users and stakeholders', 'Communicate and adapt product decisions'],
    productOwnerResponsibilityAr: ['امتلاك ترتيب قائمة مهام المنتج', 'تعظيم القيمة نحو هدف المنتج', 'جعل المقايضات شفافة', 'طلب الأدلة من المستخدمين وأصحاب المصلحة', 'إيصال قرارات المنتج والتكييف'],
    notProductOwnerResponsibility: ['Micromanage Developers’ implementation tasks', 'Promise every request or fixed scope without trade-offs', 'Replace the Scrum Master as process coach', 'Maintain private competing priority lists', 'Accept work without agreed evidence'],
    notProductOwnerResponsibilityAr: ['الإدارة الدقيقة لمهام تنفيذ المطورين', 'وعد بكل طلب أو نطاق ثابت دون مقايضات', 'استبدال سكرم ماستر كمدرب عملية', 'الاحتفاظ بقوائم أولويات خاصة متنافسة', 'قبول العمل دون أدلة متفق عليها'],
    guidedExercise: exercise({
      id: `d${dayNumber}-guided`,
      title: `${summary.title}: guided Meridian application`,
      titleAr: `${summary.titleAr}: تطبيق موجّه على ميريديان`,
      instructions: `Use the case narrative to create the first two rows of your ${summary.artifactName}. State the problem, target outcome, evidence, and a Product Owner decision.`,
      instructionsAr: `استخدم سرد الحالة لإنشاء أول صفين من ${detail.artifactNameAr}. اذكر المشكلة والنتيجة المستهدفة والدليل وقرار مالك المنتج.`,
      hints: ['Start with the user problem, not a feature', 'Connect your decision to a measurable outcome', 'Write what evidence could change your mind'],
      hintsAr: ['ابدأ بمشكلة المستخدم لا بميزة', 'اربط قرارك بنتيجة قابلة للقياس', 'اكتب ما الأدلة التي قد تغيّر رأيك'],
      modelAnswer: `Problem: ${detail.problem}\nOutcome: ${detail.outcome}\nDecision: ${detail.decision}\nEvidence: receipt timing, cycle counts, and user observation.\nReview: inspect the evidence at Sprint Review before expanding scope.`,
      modelAnswerAr: `المشكلة: ${detail.problemAr}\nالنتيجة: ${detail.outcomeAr}\nالقرار: ${detail.decisionAr}\nالدليل: توقيت الإيصال والجرد الدوري وملاحظة المستخدم.\nالمراجعة: افحص الأدلة في مراجعة السباق قبل توسيع النطاق.`,
      scoringCriteria: ['Names a Meridian user and problem', 'States an outcome', 'Makes an explicit trade-off', 'Names inspectable evidence'],
      difficulty: 'guided',
    }),
    independentExercise: exercise({
      id: `d${dayNumber}-independent`,
      title: `${summary.title}: independent decision`,
      titleAr: `${summary.titleAr}: قرار مستقل`,
      instructions: `Finance asks for an audit report while Warehouse asks for speed. Apply today’s topic to choose what comes next, document what you defer, and draft a six-sentence stakeholder reply.`,
      instructionsAr: 'تطلب المالية تقرير تدقيق بينما يطلب المستودع السرعة. طبّق موضوع اليوم لاختيار ما يأتي تاليًا، وثّق ما تؤجله، وصِغ ردًا لأصحاب المصلحة في ست جمل.',
      modelAnswer: `I will prioritize the work with the strongest evidence of advancing ${detail.outcome}. I will document the other request as deferred, not rejected, with its assumptions and review trigger. I will explain the choice to Finance and Warehouse using the Product Goal, the operational risk, and the evidence we will inspect.`,
      modelAnswerAr: `سأعطي الأولوية للعمل ذي أقوى أدلة على تقديم ${detail.outcomeAr}. سأوثّق الطلب الآخر كمؤجّل لا مرفوض مع افتراضاته ومحفز مراجعته. سأشرح الاختيار للمالية والمستودع باستخدام هدف المنتج والمخاطر التشغيلية والأدلة التي سنفحصها.`,
      scoringCriteria: ['Uses topic-specific reasoning', 'States a choice and a deferral', 'Uses evidence and Product Goal', 'Professional stakeholder communication'],
      difficulty: dayNumber >= 16 ? 'professional' : 'independent',
    }),
    stakeholderScenario: decision({
      id: `d${dayNumber}-stakeholder`,
      title: 'Competing Meridian demands',
      titleAr: 'مطالب ميريديان المتنافسة',
      context: narrative,
      contextAr: narrativeAr,
      conflict: 'Warehouse wants speed, Finance wants audit certainty, and Customer Service wants availability answers immediately; capacity covers only one focused slice.',
      conflictAr: 'المستودع يريد السرعة، والمالية تريد يقين التدقيق، وخدمة العملاء تريد إجابات التوافر فورًا؛ السعة تغطي شريحة مركّزة واحدة فقط.',
      question: 'How will you respond as Product Owner?',
      questionAr: 'كيف ستستجيب كمالك منتج؟',
      options: ['Add all demands to the Sprint', 'Use evidence and the Product Goal to order one slice, document the trade-off, and communicate a review point', 'Choose the most senior stakeholder’s request without analysis', 'Ask the team to keep three secret lists'],
      optionsAr: ['إضافة كل المطالب إلى السباق', 'استخدام الأدلة وهدف المنتج لترتيب شريحة واحدة وتوثيق المقايضة وإيصال نقطة مراجعة', 'اختيار طلب أعلى صاحب مصلحة دون تحليل', 'طلب أن يحتفظ الفريق بثلاث قوائم سرية'],
      modelAnswer: 'Use evidence and the Product Goal to order one slice, document the trade-off, and communicate a review point',
      modelAnswerAr: 'استخدام الأدلة وهدف المنتج لترتيب شريحة واحدة وتوثيق المقايضة وإيصال نقطة مراجعة',
      feedbackRubric: ['Protects one transparent Product Backlog', 'Makes a clear trade-off', 'Connects choice to outcome evidence', 'Communicates respectfully'],
    }),
    productDecisionChallenge: decision({
      id: `d${dayNumber}-decision`,
      title: 'Defend the next decision',
      titleAr: 'ادافع عن القرار التالي',
      context: `The current evidence is incomplete, but leadership asks for a final answer about ${summary.title}.`,
      contextAr: `الأدلة الحالية غير مكتملة، لكن القيادة تطلب إجابة نهائية عن ${summary.titleAr}.`,
      conflict: 'A quick promise may please leadership today but could send the team toward the wrong solution.',
      conflictAr: 'وعد سريع قد يرضي القيادة اليوم لكنه قد يدفع الفريق نحو الحل الخاطئ.',
      question: 'What decision do you make now?',
      questionAr: 'أي قرار تتخذه الآن؟',
      modelAnswer: `I will ${detail.decision}. I will be explicit about the evidence and assumptions, keep the alternative visible in the Product Backlog, and review the decision against ${detail.outcome}.`,
      modelAnswerAr: `سأقوم بـ ${detail.decisionAr}. سأكون صريحًا بشأن الأدلة والافتراضات، وأبقي البديل مرئيًا في قائمة المهام، وأراجع القرار مقابل ${detail.outcomeAr}.`,
      feedbackRubric: ['Clear decision', 'Evidence and assumptions named', 'Trade-off visible', 'Adaptation trigger included'],
    }),
    artifactActivity: artifact({
      id: `d${dayNumber}-artifact`,
      title: summary.artifactName,
      titleAr: detail.artifactNameAr,
      description: `Create a working ${summary.artifactName} for Horizon ERP Inventory & Warehouse.`,
      descriptionAr: `أنشئ ${detail.artifactNameAr} عمليًا لمخزون ومستودع Horizon ERP.`,
      template: `# ${summary.artifactName}\n${detail.artifactFields.map((field) => `${field}:`).join('\n')}\n`,
      templateAr: `# ${detail.artifactNameAr}\n${detail.artifactFieldsAr.map((field) => `${field}:`).join('\n')}\n`,
      instructions: 'Complete every field with specific Meridian evidence. Do not paste generic Agile language; show the decision and its review condition.',
      instructionsAr: 'أكمل كل حقل بأدلة ميريديان المحددة. لا تلصق لغة أجايل عامة؛ أظهر القرار وشرط مراجعته.',
      modelArtifact: `# ${summary.artifactName}\n${detail.artifactFields[0]}: ${detail.problem}\n${detail.artifactFields[1]}: ${detail.outcome}\n${detail.artifactFields[2]}: Warehouse Operator and Customer Service Agent\n${detail.artifactFields[3]}: ${detail.decision}\n${detail.artifactFields[4]}: Receipt timestamps, cycle-count variance, and user observation\n${detail.artifactFields[5] ?? 'Review'}: Inspect at the next Sprint Review\n`,
      modelArtifactAr: `# ${detail.artifactNameAr}\n${detail.artifactFieldsAr[0]}: ${detail.problemAr}\n${detail.artifactFieldsAr[1]}: ${detail.outcomeAr}\n${detail.artifactFieldsAr[2]}: مشغّل المستودع ووكيل خدمة العملاء\n${detail.artifactFieldsAr[3]}: ${detail.decisionAr}\n${detail.artifactFieldsAr[4]}: طوابع وقت الإيصال وتباين الجرد الدوري وملاحظة المستخدم\n${detail.artifactFieldsAr[5] ?? 'المراجعة'}: الفحص في مراجعة السباق التالية\n`,
      scoringCriteria: ['All required fields completed', 'Meridian-specific evidence', 'Outcome-based decision', 'Explicit trade-off', 'Review condition included'],
      requiredFields: detail.artifactFields.map((field) => `${field}:`),
    }),
    caseStudyUpdate: caseUpdate({
      dayFocus: summary.title,
      dayFocusAr: summary.titleAr,
      narrative,
      narrativeAr,
      newInformation: `A sponsor says: “Skip analysis. I need this solution now.” Warehouse operators report that ${detail.problem}.`,
      newInformationAr: `يقول راعٍ: «تخطَّ التحليل. أحتاج هذا الحل الآن.» ويبلّغ مشغّلو المستودع أن ${detail.problemAr}.`,
      requiredAction: 'Draft a professional reply that acknowledges urgency, states the evidence-based next action, and explains what will be inspected.',
      requiredActionAr: 'صِغ ردًا مهنيًا يعترف بالإلحاح ويذكر الإجراء التالي القائم على الأدلة ويشرح ما سيُفحص.',
      modelResponse: `Thank you for raising the urgency. I will treat the requested solution as an important input, not an automatic commitment. The current product concern is that ${detail.problem}. To advance ${detail.outcome}, I will ${detail.decision}. I will share the evidence, trade-off, and review point with Finance, Warehouse, and Customer Service so we can adapt based on results rather than assumptions.`,
      modelResponseAr: `شكرًا لإبراز الإلحاح. سأعامل الحل المطلوب كمدخل مهم لا كالتزام تلقائي. القلق الحالي للمنتج هو أن ${detail.problemAr}. لتقديم ${detail.outcomeAr}، سأقوم بـ ${detail.decisionAr}. سأشارك الأدلة والمقايضة ونقطة المراجعة مع المالية والمستودع وخدمة العملاء لنستطيع التكييف بناءً على النتائج لا الافتراضات.`,
    }),
    quiz, exam,
    interviewPrep: interview({
      question: `How have you used ${summary.title} to make a difficult Product Owner decision?`,
      questionAr: `كيف استخدمت ${summary.titleAr} لاتخاذ قرار صعب كمالك منتج؟`,
      modelAnswer: `I begin with the user and business problem, then identify the outcome and evidence that matter. In Meridian’s Horizon ERP product, ${detail.problem}. I would ${detail.decision} because it supports ${detail.outcome}. I make the trade-off visible in ${summary.artifactName}, communicate it to stakeholders, and inspect results before expanding the solution.`,
      modelAnswerAr: `أبدأ بمشكلة المستخدم والعمل، ثم أحدد النتيجة والأدلة المهمة. في منتج Horizon ERP لميريديان، ${detail.problemAr}. سأقوم بـ ${detail.decisionAr} لأنه يدعم ${detail.outcomeAr}. أجعل المقايضة مرئية في ${detail.artifactNameAr}، وأوصلها لأصحاب المصلحة، وأفحص النتائج قبل توسيع الحل.`,
      followUps: ['How did you handle disagreement?', 'What evidence would change your mind?', 'What did you defer and why?'],
      followUpsAr: ['كيف تعاملت مع الخلاف؟', 'أي أدلة ستغيّر رأيك؟', 'ماذا أجّلت ولماذا؟'],
      scoringCriteria: ['Explains the concept accurately', 'Uses a specific ERP example', 'Makes a trade-off explicit', 'Includes evidence and adaptation'],
    }),
    lessonSummary: [`${summary.title} supports a real Product Owner decision, not paperwork.`, `Meridian focus: ${detail.outcome}.`, 'Evidence, user needs, and the Product Goal guide trade-offs.', 'One transparent Product Backlog prevents political prioritization.', `The day artifact is ${summary.artifactName}.`, 'Inspect results and adapt rather than defend assumptions.'],
    lessonSummaryAr: [`يدعم ${summary.titleAr} قرار مالك منتج حقيقي لا أوراقًا.`, `تركيز ميريديان: ${detail.outcomeAr}.`, 'الأدلة واحتياجات المستخدم وهدف المنتج توجّه المقايضات.', 'قائمة مهام منتج شفافة واحدة تمنع الأولوية السياسية.', `مخرج اليوم هو ${detail.artifactNameAr}.`, 'افحص النتائج وتكيّف بدل الدفاع عن الافتراضات.'],
    revisionChecklist: ['Read all eight concepts', 'Answer active-learning prompts', 'Complete guided exercise', 'Complete independent exercise', 'Submit the artifact', 'Resolve stakeholder scenario', 'Attempt all ten quiz questions', 'Attempt all five exam scenarios', 'Practice interview response'],
    revisionChecklistAr: ['اقرأ المفاهيم الثمانية كلها', 'أجب عن مطالبات التعلم النشط', 'أكمل التمرين الموجّه', 'أكمل التمرين المستقل', 'أرسل المخرج', 'حل سيناريو أصحاب المصلحة', 'حاول أسئلة الاختبار العشرة', 'حاول سيناريوهات الامتحان الخمسة', 'تمرّن على رد المقابلة'],
    additionalPractice: exercise({
      id: `d${dayNumber}-teachback`,
      title: `${summary.title}: teach-back`,
      titleAr: `${summary.titleAr}: إعادة الشرح`,
      instructions: `Teach a new Product Owner how to apply today’s topic at Meridian. Include the problem, outcome, decision, common mistake, and evidence loop.`,
      instructionsAr: 'علّم مالك منتج جديد كيفية تطبيق موضوع اليوم في ميريديان. تضمّن المشكلة والنتيجة والقرار والخطأ الشائع وحلقة الأدلة.',
      modelAnswer: `A strong teach-back explains that ${summary.title} is used to make an evidence-based choice. At Meridian, ${detail.problem}; the PO should ${detail.decision} to pursue ${detail.outcome}, then inspect real operational evidence and adapt.`,
      modelAnswerAr: `إعادة شرح قوية توضح أن ${summary.titleAr} يُستخدم لاتخاذ اختيار قائم على الأدلة. في ميريديان، ${detail.problemAr}؛ يجب على مالك المنتج ${detail.decisionAr} لتحقيق ${detail.outcomeAr}، ثم فحص الأدلة التشغيلية الحقيقية والتكييف.`,
      scoringCriteria: ['Plain-language explanation', 'Specific Meridian example', 'Decision and outcome', 'Evidence loop'],
      difficulty: 'independent',
    }),
    professionalFeedbackNotes: ['Generic statements score poorly; use the Meridian facts.', 'A request is not a commitment until the Product Owner orders it.', 'Name what you will inspect, not just what you will build.', 'Show the trade-off and how stakeholders will hear it.', 'Use the product artifact as a living decision record.'],
  };
}
