import type { AssessmentQuestion } from '@/po/types';

/** Initial readiness assessment — no prior PO/Agile/Scrum knowledge assumed. */
export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'a1', type: 'multiple_choice', topic: 'product_ownership', difficulty: 'easy', points: 5,
    question: 'In plain language, what is a product?',
    options: [
      'A temporary project with a fixed end date',
      'Something that delivers value to users over time and can evolve',
      'A list of developer tasks',
      'A contract with a vendor',
    ],
    correctAnswer: 'Something that delivers value to users over time and can evolve',
    explanation: 'A product is a value vehicle that continues and improves; a project is temporary.',
  },
  {
    id: 'a2', type: 'multiple_choice', topic: 'product_ownership', difficulty: 'easy', points: 5,
    question: 'What is the Product Owner primarily accountable for?',
    options: [
      'Writing all of the code',
      'Maximizing the value of the product',
      'Approving employee vacations',
      'Facilitating every meeting',
    ],
    correctAnswer: 'Maximizing the value of the product',
    explanation: 'Value maximization is the core PO accountability in Scrum.',
  },
  {
    id: 'a3', type: 'multiple_choice', topic: 'agile_mindset', difficulty: 'easy', points: 5,
    question: 'Agile delivery emphasizes:',
    options: [
      'Delivering the entire solution only at the end with no feedback',
      'Learning through small increments and adapting based on feedback',
      'Avoiding customer contact until launch',
      'Freezing all requirements on day one forever',
    ],
    correctAnswer: 'Learning through small increments and adapting based on feedback',
    explanation: 'Agile is built on iterative/incremental delivery and feedback loops.',
  },
  {
    id: 'a4', type: 'multiple_choice', topic: 'scrum_framework', difficulty: 'easy', points: 5,
    question: 'Scrum is best described as:',
    options: [
      'A project management software tool',
      'A lightweight framework for generating value through adaptive solutions',
      'A documentation standard only',
      'A coding language',
    ],
    correctAnswer: 'A lightweight framework for generating value through adaptive solutions',
    explanation: 'Scrum is a framework based on empiricism and lean thinking.',
  },
  {
    id: 'a5', type: 'multiple_choice', topic: 'roles_collaboration', difficulty: 'medium', points: 5,
    question: 'Who orders the Product Backlog?',
    options: [
      'The Scrum Master',
      'Any stakeholder who emails the team',
      'The Product Owner',
      'The steering committee by daily vote',
    ],
    correctAnswer: 'The Product Owner',
    explanation: 'A single Product Owner orders the Product Backlog.',
  },
  {
    id: 'a6', type: 'multiple_choice', topic: 'vision_strategy', difficulty: 'medium', points: 5,
    question: 'A Product Goal should primarily describe:',
    options: [
      'A long list of UI colors',
      'A future state of the product that the team plans for',
      'The project Gantt chart',
      'Developer vacation plans',
    ],
    correctAnswer: 'A future state of the product that the team plans for',
    explanation: 'The Product Goal is a long-term objective for the Scrum Team.',
  },
  {
    id: 'a7', type: 'multiple_choice', topic: 'stakeholders', difficulty: 'medium', points: 5,
    question: 'A user and a customer are:',
    options: [
      'Always the same person',
      'Sometimes different — the user uses the product; the customer buys/sponsors it',
      'Both identical to the Product Owner',
      'Irrelevant in ERP products',
    ],
    correctAnswer: 'Sometimes different — the user uses the product; the customer buys/sponsors it',
    explanation: 'In ERP, warehouse operators may use the product while leadership sponsors purchase.',
  },
  {
    id: 'a8', type: 'multiple_choice', topic: 'product_discovery', difficulty: 'medium', points: 5,
    question: 'Why validate the problem before building a requested solution?',
    options: [
      'To delay work indefinitely',
      'Because the requested solution may not address the real problem',
      'Because Developers refuse requirements',
      'Because Agile forbids solutions',
    ],
    correctAnswer: 'Because the requested solution may not address the real problem',
    explanation: 'Discovery prevents building the wrong thing efficiently.',
  },
  {
    id: 'a9', type: 'multiple_choice', topic: 'user_stories', difficulty: 'medium', points: 5,
    question: 'A good User Story focuses on:',
    options: [
      'Technical database indexes only',
      'Who the user is, what they need, and why it matters',
      'Project status colors',
      'How many meetings were held',
    ],
    correctAnswer: 'Who the user is, what they need, and why it matters',
    explanation: 'User Stories communicate user value, not implementation trivia alone.',
  },
  {
    id: 'a10', type: 'multiple_choice', topic: 'acceptance_criteria', difficulty: 'medium', points: 5,
    question: 'Acceptance Criteria should be:',
    options: [
      'Vague so the team stays flexible',
      'Testable conditions that clarify when a backlog item is acceptably done from a product perspective',
      'Written only after release',
      'Identical to the company vision statement',
    ],
    correctAnswer: 'Testable conditions that clarify when a backlog item is acceptably done from a product perspective',
    explanation: 'AC make value verifiable and reduce ambiguity.',
  },
  {
    id: 'a11', type: 'scenario', topic: 'prioritization', difficulty: 'medium', points: 10,
    question: 'Everything is labeled urgent. What should a Product Owner do?',
    options: [
      'Put all items in the Sprint',
      'Compare value, risk, urgency, and dependencies against goals; order transparently; negotiate',
      'Pick randomly',
      'Hide the backlog',
    ],
    correctAnswer: 'Compare value, risk, urgency, and dependencies against goals; order transparently; negotiate',
    explanation: 'Priority is a decision, not a mood. Transparency and rationale build trust.',
  },
  {
    id: 'a12', type: 'scenario', topic: 'sprint_execution', difficulty: 'medium', points: 10,
    question: 'Mid-Sprint, a sponsor demands a new feature unrelated to the Sprint Goal. Best response?',
    options: [
      'Add it immediately without discussion',
      'Protect the Sprint Goal; place the request on the Product Backlog; negotiate trade-offs if truly critical',
      'Quit the role',
      'Ask Developers to work nights secretly',
    ],
    correctAnswer: 'Protect the Sprint Goal; place the request on the Product Backlog; negotiate trade-offs if truly critical',
    explanation: 'Sprint Goal protection preserves focus and empiricism.',
  },
  {
    id: 'a13', type: 'multiple_choice', topic: 'quality_acceptance', difficulty: 'medium', points: 5,
    question: 'Accepting an Increment should be based on:',
    options: [
      'Friendship with Developers',
      'Evidence against Acceptance Criteria and Definition of Done',
      'Whether the demo looked pretty',
      'Whether the date arrived',
    ],
    correctAnswer: 'Evidence against Acceptance Criteria and Definition of Done',
    explanation: 'Acceptance is evidence-based.',
  },
  {
    id: 'a14', type: 'multiple_choice', topic: 'roadmaps_metrics', difficulty: 'hard', points: 5,
    question: 'Which is a vanity metric risk?',
    options: [
      'Inventory accuracy percentage tied to a Product Goal',
      'Counting features shipped with no outcome change',
      'Time to confirm available stock',
      'Reduction in delayed shipments',
    ],
    correctAnswer: 'Counting features shipped with no outcome change',
    explanation: 'Output without outcome can mislead stakeholders.',
  },
  {
    id: 'a15', type: 'scenario', topic: 'professional_practice', difficulty: 'hard', points: 10,
    question: 'A stakeholder says: "Build AI for warehouse planning this quarter." You have weak problem evidence. Best first move?',
    options: [
      'Commit to AI immediately',
      'Investigate the problem, separate problem from solution, define outcomes, then decide backlog order',
      'Reject all innovation forever',
      'Transfer accountability to IT support',
    ],
    correctAnswer: 'Investigate the problem, separate problem from solution, define outcomes, then decide backlog order',
    explanation: 'Professional POs validate problems before expensive solution commitments.',
  },
  {
    id: 'a16', type: 'multiple_choice', topic: 'backlog_management', difficulty: 'medium', points: 5,
    question: 'The Product Backlog is:',
    options: [
      'An unordered email inbox',
      'An emergent, ordered list of what is needed to improve the product',
      'The Sprint Retrospective notes only',
      'A closed contract that never changes',
    ],
    correctAnswer: 'An emergent, ordered list of what is needed to improve the product',
    explanation: 'The Product Backlog is living and ordered.',
  },
  {
    id: 'a17', type: 'multiple_choice', topic: 'refinement', difficulty: 'medium', points: 5,
    question: 'Backlog refinement exists to:',
    options: [
      'Replace Sprint Reviews',
      'Break down and clarify upcoming items so they are better understood and ready for planning',
      'Punish Developers',
      'Create more status reports',
    ],
    correctAnswer: 'Break down and clarify upcoming items so they are better understood and ready for planning',
    explanation: 'Refinement improves readiness and understanding.',
  },
  {
    id: 'a18', type: 'multiple_choice', topic: 'estimation_forecasting', difficulty: 'medium', points: 5,
    question: 'Story points are best treated as:',
    options: [
      'Exact hour commitments signed by the PO',
      'Relative complexity/effort signals used for forecasting, not false certainty',
      'Salary metrics',
      'Bug severity codes',
    ],
    correctAnswer: 'Relative complexity/effort signals used for forecasting, not false certainty',
    explanation: 'Estimates support forecasting; they are not contracts.',
  },
  {
    id: 'a19', type: 'multiple_choice', topic: 'review_retrospective', difficulty: 'easy', points: 5,
    question: 'Sprint Review primarily inspects:',
    options: [
      'Only team feelings',
      'The Increment and adapts the Product Backlog with stakeholders',
      'HR policies',
      'Vendor invoices only',
    ],
    correctAnswer: 'The Increment and adapts the Product Backlog with stakeholders',
    explanation: 'Review is a product inspection event.',
  },
  {
    id: 'a20', type: 'scenario', topic: 'product_ownership', difficulty: 'hard', points: 10,
    question: 'Five managers keep separate Excel priority lists and WhatsApp Developers directly. Your first professional move?',
    options: [
      'Allow it for speed',
      'Establish one transparent Product Backlog with PO ordering and a clear request channel',
      'Create five Sprint Backlogs',
      'Delete all communication',
    ],
    correctAnswer: 'Establish one transparent Product Backlog with PO ordering and a clear request channel',
    explanation: 'Single ordered backlog and clear channels restore transparency and focus.',
  },
];
