import type { DaySummary } from '@/po/types';

export const DAY_SUMMARIES: DaySummary[] = [
  { dayNumber: 1, title: 'Products, Projects, and Product Ownership', titleAr: 'المنتجات والمشاريع وملكية المنتج', subtitle: 'What a Product Owner owns and why it matters', subtitleAr: 'ما يملكه مالك المنتج ولماذا يهم', topics: ['product_ownership'], estimatedHours: 4, week: 1, difficulty: 'foundation', artifactName: 'Product Owner Responsibility Map' },
  { dayNumber: 2, title: 'Agile Foundations and Mindset', titleAr: 'أساسيات أجايل والعقلية', subtitle: 'Values, principles, feedback, and outcomes', subtitleAr: 'القيم والمبادئ والتغذية الراجعة والنتائج', topics: ['agile_mindset'], estimatedHours: 4, week: 1, difficulty: 'foundation', artifactName: 'Agile Delivery Transformation Plan' },
  { dayNumber: 3, title: 'Scrum Framework', titleAr: 'إطار عمل سكرم', subtitle: 'Theory, team, events, artifacts, commitments', subtitleAr: 'النظرية والفريق والأحداث والمخرجات والالتزامات', topics: ['scrum_framework'], estimatedHours: 5, week: 1, difficulty: 'foundation', artifactName: 'Complete Scrum Framework Map' },
  { dayNumber: 4, title: 'Product Roles and Responsibilities', titleAr: 'أدوار المنتج والمسؤوليات', subtitle: 'Boundaries, collaboration, and RACI clarity', subtitleAr: 'الحدود والتعاون ووضوح المسؤوليات', topics: ['roles_collaboration'], estimatedHours: 4, week: 1, difficulty: 'foundation', artifactName: 'Product Team Responsibility Matrix' },
  { dayNumber: 5, title: 'Product Vision, Strategy, and Goals', titleAr: 'رؤية المنتج والاستراتيجية والأهداف', subtitle: 'Connect daily work to strategic intent', subtitleAr: 'ربط العمل اليومي بالقصد الاستراتيجي', topics: ['vision_strategy'], estimatedHours: 4, week: 1, difficulty: 'foundation', artifactName: 'Product Vision Board and Product Goal' },
  { dayNumber: 6, title: 'Stakeholders, Customers, and Users', titleAr: 'أصحاب المصلحة والعملاء والمستخدمون', subtitle: 'Identify, analyze, negotiate, and communicate', subtitleAr: 'التحديد والتحليل والتفاوض والتواصل', topics: ['stakeholders'], estimatedHours: 4, week: 2, difficulty: 'guided_practitioner', artifactName: 'Stakeholder Map and Communication Plan' },
  { dayNumber: 7, title: 'Product Discovery and Problem Analysis', titleAr: 'اكتشاف المنتج وتحليل المشكلة', subtitle: 'Validate problems before building solutions', subtitleAr: 'التحقق من المشكلات قبل بناء الحلول', topics: ['product_discovery'], estimatedHours: 5, week: 2, difficulty: 'guided_practitioner', artifactName: 'Product Discovery Brief' },
  { dayNumber: 8, title: 'Requirements and Backlog Hierarchy', titleAr: 'المتطلبات وتسلسل قائمة المهام', subtitle: 'From business need to backlog structure', subtitleAr: 'من الحاجة التجارية إلى هيكل قائمة المهام', topics: ['requirements'], estimatedHours: 4, week: 2, difficulty: 'guided_practitioner', artifactName: 'Requirements and Backlog Hierarchy' },
  { dayNumber: 9, title: 'Professional User Stories', titleAr: 'قصص المستخدم الاحترافية', subtitle: 'Value-focused, INVEST-ready stories', subtitleAr: 'قصص تركز على القيمة وجاهزة وفق INVEST', topics: ['user_stories'], estimatedHours: 5, week: 2, difficulty: 'guided_practitioner', artifactName: 'Professional User Story Collection' },
  { dayNumber: 10, title: 'Acceptance Criteria and Business Rules', titleAr: 'معايير القبول وقواعد العمل', subtitle: 'Make value testable and unambiguous', subtitleAr: 'اجعل القيمة قابلة للاختبار وغير غامضة', topics: ['acceptance_criteria'], estimatedHours: 4, week: 2, difficulty: 'guided_practitioner', artifactName: 'Acceptance Criteria and Example Map' },
  { dayNumber: 11, title: 'Building and Managing the Product Backlog', titleAr: 'بناء وإدارة قائمة مهام المنتج', subtitle: 'A living, ordered source of truth', subtitleAr: 'مصدر حقيقة حي ومرتب', topics: ['backlog_management'], estimatedHours: 4, week: 3, difficulty: 'independent_practitioner', artifactName: 'Complete Product Backlog' },
  { dayNumber: 12, title: 'Product Backlog Prioritization', titleAr: 'تحديد أولويات قائمة مهام المنتج', subtitle: 'Decide what comes next — and why', subtitleAr: 'قرر ماذا يأتي بعد ذلك — ولماذا', topics: ['prioritization'], estimatedHours: 5, week: 3, difficulty: 'independent_practitioner', artifactName: 'Prioritized Backlog with Decision Rationale' },
  { dayNumber: 13, title: 'Estimation, Capacity, and Forecasting', titleAr: 'التقدير والسعة والتنبؤ', subtitle: 'Plan with uncertainty without false certainty', subtitleAr: 'خطط مع عدم اليقين دون يقين زائف', topics: ['estimation_forecasting'], estimatedHours: 4, week: 3, difficulty: 'independent_practitioner', artifactName: 'Estimated Product Backlog and Forecast' },
  { dayNumber: 14, title: 'Backlog Refinement', titleAr: 'تنقيح قائمة المهام', subtitle: 'Make upcoming work Sprint-ready', subtitleAr: 'اجعل العمل القادم جاهزًا للسباق', topics: ['refinement'], estimatedHours: 4, week: 3, difficulty: 'independent_practitioner', artifactName: 'Sprint-Ready Backlog' },
  { dayNumber: 15, title: 'Sprint Planning and Sprint Goals', titleAr: 'تخطيط السباق وأهداف السباق', subtitle: 'Select valuable work for a coherent Sprint', subtitleAr: 'اختر عملاً ذا قيمة لسباق متماسك', topics: ['sprint_planning'], estimatedHours: 4, week: 3, difficulty: 'independent_practitioner', artifactName: 'Sprint Goal and Sprint Plan' },
  { dayNumber: 16, title: 'Product Owner Work During the Sprint', titleAr: 'عمل مالك المنتج أثناء السباق', subtitle: 'Clarify, decide, and protect the Sprint Goal', subtitleAr: 'وضّح وقرر واحمِ هدف السباق', topics: ['sprint_execution'], estimatedHours: 4, week: 4, difficulty: 'professional', artifactName: 'Product Owner Decision Log' },
  { dayNumber: 17, title: 'Quality, Testing, and Product Acceptance', titleAr: 'الجودة والاختبار وقبول المنتج', subtitle: 'Accept evidence, not assumptions', subtitleAr: 'اقبل الأدلة لا الافتراضات', topics: ['quality_acceptance'], estimatedHours: 4, week: 4, difficulty: 'professional', artifactName: 'UAT and Product Acceptance Report' },
  { dayNumber: 18, title: 'Sprint Review, Retrospective, and Feedback', titleAr: 'مراجعة السباق والاستعراض بأثر رجعي والتغذية الراجعة', subtitle: 'Inspect the product and improve the system', subtitleAr: 'افحص المنتج وحسّن النظام', topics: ['review_retrospective'], estimatedHours: 4, week: 4, difficulty: 'professional', artifactName: 'Sprint Review and Improvement Report' },
  { dayNumber: 19, title: 'Roadmaps, Releases, and Product Metrics', titleAr: 'خرائط الطريق والإصدارات ومقاييس المنتج', subtitle: 'Communicate direction and measure outcomes', subtitleAr: 'بلّغ الاتجاه وقِس النتائج', topics: ['roadmaps_metrics'], estimatedHours: 5, week: 4, difficulty: 'professional', artifactName: 'Roadmap, Release Plan, and Metrics Framework' },
  { dayNumber: 20, title: 'Complete Professional Product Owner Simulation', titleAr: 'محاكاة مالك منتج احترافية كاملة', subtitle: 'Job-ready end-to-end Product Ownership', subtitleAr: 'ملكية منتج جاهزة للعمل من البداية للنهاية', topics: ['professional_practice'], estimatedHours: 6, week: 4, difficulty: 'simulation', artifactName: 'Professional Product Owner Portfolio' },
];

export function getDaySummary(dayNumber: number): DaySummary | undefined {
  return DAY_SUMMARIES.find((d) => d.dayNumber === dayNumber);
}

export function getWeekDays(week: number): DaySummary[] {
  return DAY_SUMMARIES.filter((d) => d.week === week);
}
