import type { Term } from '@/po/types';

function term(partial: Term): Term {
  return partial;
}

export const TERMINOLOGY: Term[] = [
  term({
    key: 'agile', term: 'Agile', termAr: 'أجايل',
    simpleMeaning: 'A way of working that delivers value in small steps and learns from feedback instead of planning everything rigidly up front.',
    simpleMeaningAr: 'طريقة عمل تُسلّم القيمة بخطوات صغيرة وتتعلم من التغذية الراجعة.',
    professionalDefinition: 'A family of adaptive approaches based on iterative and incremental delivery, customer collaboration, and responding to change.',
    purpose: 'Reduce the risk of building the wrong thing and improve time-to-learning.',
    lifecycleLocation: 'Across strategy, discovery, delivery, and adaptation.',
    responsibleRole: 'Whole organization culture; Product Owner applies it to value decisions.',
    participants: 'Product Owner, Developers, Scrum Master, stakeholders, users.',
    inputs: 'Goals, feedback, constraints.',
    outputs: 'Increments, adapted plans, outcome learning.',
    example: 'A cafe tests a new sandwich for one week, measures sales, then adapts the menu.',
    softwareExample: 'Ship a thin checkout improvement, measure conversion, then decide next change.',
    erpExample: 'Release receiving improvements for Warehouse A, measure accuracy, then expand.',
    relatedTerms: ['scrum', 'iterative', 'incremental', 'outcome'],
    confusedWith: 'Scrum (Scrum is one Agile framework)',
    incorrectUsage: 'Calling any standup "Agile" while freezing scope for 9 months.',
    correctUsage: 'Using feedback loops and incremental value delivery intentionally.',
    category: 'Agile',
  }),
  term({
    key: 'scrum', term: 'Scrum', termAr: 'سكرم',
    simpleMeaning: 'A simple framework with roles, events, and artifacts that helps teams deliver value in short Sprints.',
    simpleMeaningAr: 'إطار بسيط بأدوار وأحداث ومخرجات يساعد الفرق على تسليم القيمة في سباقات قصيرة.',
    professionalDefinition: 'A lightweight framework that helps people, teams, and organizations generate value through adaptive solutions for complex problems.',
    purpose: 'Enable empiricism: transparency, inspection, adaptation.',
    lifecycleLocation: 'Delivery operating system inside product lifecycle.',
    responsibleRole: 'Scrum Team collectively; PO for product value.',
    participants: 'Product Owner, Scrum Master, Developers, stakeholders at Review.',
    inputs: 'Product Goal, Product Backlog, team capacity, feedback.',
    outputs: 'Done Increment, Sprint Goal outcomes, adapted backlog/process.',
    example: 'A school club plans a weekly goal, works for a week, shows results, improves how they work.',
    softwareExample: 'Two-week Sprints producing usable product Increments.',
    erpExample: 'Meridian Inventory team delivers a usable receiving Increment each Sprint.',
    relatedTerms: ['agile', 'sprint', 'product_backlog', 'increment'],
    confusedWith: 'Agile (broader), Kanban, project methodology checklist',
    incorrectUsage: 'Using Scrum events as status reporting theater without adaptation.',
    correctUsage: 'Using Scrum to inspect product and process and adapt based on evidence.',
    category: 'Scrum',
  }),
  term({
    key: 'product', term: 'Product', termAr: 'المنتج',
    simpleMeaning: 'Something that continues to help people achieve outcomes and can be improved over time.',
    simpleMeaningAr: 'شيء يستمر في مساعدة الناس على تحقيق نتائج ويمكن تحسينه مع الوقت.',
    professionalDefinition: 'A vehicle for delivering value; managed across a lifecycle to solve user and business problems.',
    purpose: 'Create sustained outcomes, not one-time activity.',
    lifecycleLocation: 'Entire lifecycle.',
    responsibleRole: 'Product Owner (value); broader strategy may include Product Manager/sponsors.',
    participants: 'Users, customers, team, stakeholders.',
    inputs: 'Needs, strategy, constraints, feedback.',
    outputs: 'Capabilities, Increments, outcomes.',
    example: 'A bicycle brand product line that evolves yearly.',
    softwareExample: 'A mobile banking app that continuously improves.',
    erpExample: 'Horizon ERP Inventory & Warehouse.',
    relatedTerms: ['project', 'product_owner', 'product_goal'],
    confusedWith: 'Project',
    incorrectUsage: 'Calling a two-week ticket a product.',
    correctUsage: 'Naming the enduring value capability and its users/outcomes.',
    category: 'Product Ownership',
  }),
  term({
    key: 'project', term: 'Project', termAr: 'المشروع',
    simpleMeaning: 'A temporary effort with a start and end to achieve a specific result.',
    simpleMeaningAr: 'جهد مؤقت له بداية ونهاية لتحقيق نتيجة محددة.',
    professionalDefinition: 'A temporary endeavor undertaken to create a unique product, service, or result.',
    purpose: 'Organize temporary delivery constraints.',
    lifecycleLocation: 'May fund or launch parts of a product lifecycle.',
    responsibleRole: 'Project Manager for constraints; PO still owns product value.',
    participants: 'Sponsors, PM, delivery team, PO.',
    inputs: 'Charter, constraints, objectives.',
    outputs: 'Project result and closure.',
    example: 'Renovating a store in 8 weeks.',
    softwareExample: 'A fixed cutover migration weekend.',
    erpExample: 'Warehouse A opening-balance cutover project.',
    relatedTerms: ['product', 'release'],
    confusedWith: 'Product',
    incorrectUsage: 'Measuring only project dates as product success.',
    correctUsage: 'Using projects as containers when needed while product outcomes continue.',
    category: 'Product Ownership',
  }),
  term({
    key: 'product_owner', term: 'Product Owner', termAr: 'مالك المنتج',
    simpleMeaning: 'The person accountable for what the team works on and why — maximizing product value.',
    simpleMeaningAr: 'الشخص المسؤول عن ماذا تعمل عليه الفريق ولماذا — لتعظيم قيمة المنتج.',
    professionalDefinition: 'Accountable for maximizing the value of the product resulting from the work of the Scrum Team, including effective Product Backlog management.',
    purpose: 'Create clear value accountability and a single ordered backlog.',
    lifecycleLocation: 'Discovery through release and adaptation.',
    responsibleRole: 'Product Owner (one person accountable).',
    participants: 'Collaborates with Scrum Team and stakeholders.',
    inputs: 'Strategy, feedback, requests, evidence.',
    outputs: 'Product Goal, ordered backlog, accepted Increments, decisions.',
    example: 'A restaurant owner deciding seasonal menu focus.',
    softwareExample: 'PO ordering onboarding over cosmetic polish.',
    erpExample: 'PO for Horizon Inventory ordering accuracy work above unvalidated AI.',
    relatedTerms: ['product_manager', 'business_analyst', 'scrum_master'],
    confusedWith: 'Project Manager, Business Analyst, Product Manager',
    incorrectUsage: 'Using PO as a note-taker or ticket clerk.',
    correctUsage: 'Empowered value decision-maker with transparent backlog ownership.',
    category: 'Roles',
  }),
  term({
    key: 'product_manager', term: 'Product Manager', termAr: 'مدير المنتج',
    simpleMeaning: 'A broader product leadership role often covering market strategy, business case, and cross-team product direction.',
    simpleMeaningAr: 'دور قيادي أوسع للمنتج يغطي غالباً استراتيجية السوق وحالة العمل واتجاه المنتج.',
    professionalDefinition: 'A product leadership role focused on product strategy, market/customer outcomes, and coordinating product direction; may or may not act as Scrum Product Owner.',
    purpose: 'Align product with market and business strategy.',
    lifecycleLocation: 'Strategy and portfolio/product line level.',
    responsibleRole: 'Product Manager.',
    participants: 'Executives, POs, sales, marketing, engineering leaders.',
    inputs: 'Market data, strategy, financial goals.',
    outputs: 'Strategy, positioning, roadmap themes.',
    example: 'PM decides which customer segment a company serves next year.',
    softwareExample: 'PM sets platform strategy across multiple squads.',
    erpExample: 'PM for Horizon ERP suite; PO owns Inventory module backlog.',
    relatedTerms: ['product_owner', 'vision_strategy'],
    confusedWith: 'Product Owner',
    incorrectUsage: 'Assuming titles are identical in every company.',
    correctUsage: 'Clarify local RACI: who owns strategy vs Sprint-level backlog ordering.',
    category: 'Roles',
  }),
  term({
    key: 'business_analyst', term: 'Business Analyst', termAr: 'محلل الأعمال',
    simpleMeaning: 'A specialist who helps analyze problems, processes, and requirements — supporting clarity, not replacing PO accountability.',
    simpleMeaningAr: 'متخصص يساعد في تحليل المشكلات والعمليات والمتطلبات — يدعم الوضوح ولا يستبدل مساءلة مالك المنتج.',
    professionalDefinition: 'A role that facilitates understanding of business needs and requirements; collaborates with Product Owners but does not remove PO accountability for value and ordering.',
    purpose: 'Improve problem/requirement clarity.',
    lifecycleLocation: 'Discovery and refinement heavily.',
    responsibleRole: 'BA for analysis quality; PO for value decisions.',
    participants: 'PO, users, stakeholders, Developers.',
    inputs: 'Process knowledge, interviews, documents.',
    outputs: 'Analyses, requirement drafts, models.',
    example: 'BA maps current warehouse receiving steps.',
    softwareExample: 'BA documents workflow exceptions for onboarding.',
    erpExample: 'BA helps draft receiving business rules for Horizon.',
    relatedTerms: ['product_owner', 'requirements', 'user_story'],
    confusedWith: 'Product Owner',
    incorrectUsage: 'BA secretly orders the backlog.',
    correctUsage: 'BA supports analysis; PO decides order and value.',
    category: 'Roles',
  }),
  term({
    key: 'scrum_master', term: 'Scrum Master', termAr: 'سكرم ماستر',
    simpleMeaning: 'The coach/facilitator who helps the team use Scrum well and remove process obstacles.',
    simpleMeaningAr: 'المدرّب/الميسّر الذي يساعد الفريق على استخدام سكرم جيداً وإزالة عقبات العملية.',
    professionalDefinition: 'Accountable for establishing Scrum as defined in the Scrum Guide, helping everyone understand Scrum theory and practice.',
    purpose: 'Improve effectiveness of Scrum Team and organization\'s Scrum adoption.',
    lifecycleLocation: 'Throughout Sprint cycle.',
    responsibleRole: 'Scrum Master.',
    participants: 'Scrum Team and organization.',
    inputs: 'Team impediments, Scrum understanding gaps.',
    outputs: 'Coaching, facilitation, improved working agreements.',
    example: 'A coach helping a sports team improve how they practice, not playing every position.',
    softwareExample: 'SM facilitates Retrospective and coaches PO/stakeholder boundaries.',
    erpExample: 'SM helps Meridian stop WhatsApp tasking Developers mid-Sprint.',
    relatedTerms: ['scrum', 'product_owner', 'developers'],
    confusedWith: 'Project Manager, Product Owner',
    incorrectUsage: 'SM as status boss assigning tasks.',
    correctUsage: 'SM as servant-leader and Scrum coach.',
    category: 'Roles',
  }),
  term({
    key: 'developers', term: 'Developers', termAr: 'المطوّرون',
    simpleMeaning: 'The people on the Scrum Team who create the usable Increment.',
    simpleMeaningAr: 'أعضاء فريق سكرم الذين ينشئون الزيادة القابلة للاستخدام.',
    professionalDefinition: 'Scrum Team members committed to creating any aspect of a usable Increment each Sprint.',
    purpose: 'Turn selected backlog items into Done product Increments.',
    lifecycleLocation: 'Sprint Planning through Increment delivery.',
    responsibleRole: 'Developers for how work is done and Done quality.',
    participants: 'Whole Scrum Team.',
    inputs: 'Sprint Goal, selected items, clarifications.',
    outputs: 'Done Increment, Sprint Backlog adaptations.',
    example: 'Kitchen staff preparing dishes for tonight\'s service.',
    softwareExample: 'Engineers, testers, and designers creating the Increment together.',
    erpExample: 'ERP implementers/builders delivering receiving flow Increment.',
    relatedTerms: ['increment', 'definition_of_done', 'sprint_backlog'],
    confusedWith: 'Only programmers (in Scrum, Developers is broader)',
    incorrectUsage: 'PO assigning each Developer tasks hourly.',
    correctUsage: 'Developers self-manage how to achieve the Sprint Goal.',
    category: 'Roles',
  }),
  term({
    key: 'stakeholder', term: 'Stakeholder', termAr: 'صاحب مصلحة',
    simpleMeaning: 'Anyone who can affect or is affected by the product.',
    simpleMeaningAr: 'أي شخص يمكن أن يؤثر على المنتج أو يتأثر به.',
    professionalDefinition: 'An individual or group with an interest in the product\'s outcomes, including sponsors, users, customers, regulators, and partners.',
    purpose: 'Provide needs, constraints, and feedback — not to replace backlog ordering.',
    lifecycleLocation: 'All stages, especially discovery and Sprint Review.',
    responsibleRole: 'PO manages engagement; stakeholders contribute input.',
    participants: 'Varies by product.',
    inputs: 'Needs, risks, constraints, feedback.',
    outputs: 'Requests and insights for PO evaluation.',
    example: 'Parents are stakeholders in a school lunch program.',
    softwareExample: 'Support, sales, compliance, and end users.',
    erpExample: 'COO, Finance, Warehouse Supervisors, Customer Service.',
    relatedTerms: ['user', 'customer', 'sponsor'],
    confusedWith: 'User / Customer (related but not identical)',
    incorrectUsage: 'Every stakeholder can reorder the Sprint.',
    correctUsage: 'Stakeholders influence; PO decides order.',
    category: 'Stakeholders',
  }),
  term({
    key: 'user', term: 'User', termAr: 'المستخدم',
    simpleMeaning: 'The person who actually uses the product to do work or achieve a goal.',
    simpleMeaningAr: 'الشخص الذي يستخدم المنتج فعلياً لإنجاز عمل أو هدف.',
    professionalDefinition: 'The actor who interacts with the product to accomplish tasks or outcomes.',
    purpose: 'Ground product decisions in real usage.',
    lifecycleLocation: 'Discovery, story writing, UAT, adoption.',
    responsibleRole: 'PO ensures user value is represented.',
    participants: 'Users, UX, PO, BA.',
    inputs: 'Jobs-to-be-done, pains, workflows.',
    outputs: 'Personas, stories, usability feedback.',
    example: 'A librarian using a catalog system.',
    softwareExample: 'A rider using a ride-hailing app.',
    erpExample: 'Warehouse Operator posting a receipt.',
    relatedTerms: ['customer', 'persona', 'user_story'],
    confusedWith: 'Customer / Buyer',
    incorrectUsage: 'Writing stories only for executives who never use the screens.',
    correctUsage: 'Identify real hands-on users and their outcomes.',
    category: 'Stakeholders',
  }),
  term({
    key: 'customer', term: 'Customer', termAr: 'العميل',
    simpleMeaning: 'The person or organization that buys or chooses the product (may differ from the user).',
    simpleMeaningAr: 'الشخص أو المنظمة التي تشتري المنتج أو تختاره (قد تختلف عن المستخدم).',
    professionalDefinition: 'The economic buyer or choosing organization that funds or selects the product.',
    purpose: 'Capture commercial and contractual value perspective.',
    lifecycleLocation: 'Strategy, sales, success metrics.',
    responsibleRole: 'PO balances customer and user value.',
    participants: 'Buyers, sponsors, procurement.',
    inputs: 'Contracts, buying criteria, ROI expectations.',
    outputs: 'Value propositions, success criteria.',
    example: 'A parent buying software used by a child.',
    softwareExample: 'Company purchasing SaaS seats for employees.',
    erpExample: 'Meridian Manufacturing Group buying Horizon ERP.',
    relatedTerms: ['user', 'sponsor', 'buyer'],
    confusedWith: 'User',
    incorrectUsage: 'Ignoring users because the buyer is happy in demos.',
    correctUsage: 'Serve both buying outcomes and user outcomes.',
    category: 'Stakeholders',
  }),
  term({
    key: 'sponsor', term: 'Sponsor', termAr: 'الراعي',
    simpleMeaning: 'A leader who provides authority, funding, or organizational support for the product initiative.',
    simpleMeaningAr: 'قائد يوفر السلطة أو التمويل أو الدعم التنظيمي لمبادرة المنتج.',
    professionalDefinition: 'An accountable organizational leader who champions and funds the product initiative and sets strategic boundaries.',
    purpose: 'Provide mandate and remove organizational blockers.',
    lifecycleLocation: 'Chartering, governance, major trade-offs.',
    responsibleRole: 'Sponsor for mandate; PO for product value inside boundaries.',
    participants: 'Executives, PO, governance forums.',
    inputs: 'Strategy, funding, constraints.',
    outputs: 'Mandate, boundaries, escalation support.',
    example: 'A mayor sponsoring a city transit improvement.',
    softwareExample: 'CTO sponsoring a platform modernization.',
    erpExample: 'COO and Head of Supply Chain for Horizon Inventory.',
    relatedTerms: ['stakeholder', 'customer'],
    confusedWith: 'Product Owner',
    incorrectUsage: 'Sponsor directly injecting Sprint tasks daily.',
    correctUsage: 'Sponsor sets outcomes/boundaries; PO orders backlog.',
    category: 'Stakeholders',
  }),
  term({
    key: 'product_vision', term: 'Product Vision', termAr: 'رؤية المنتج',
    simpleMeaning: 'A clear picture of the future value the product should create.',
    simpleMeaningAr: 'صورة واضحة للقيمة المستقبلية التي يجب أن يصنعها المنتج.',
    professionalDefinition: 'A strategic narrative describing the intended future state and value of the product for users and the organization.',
    purpose: 'Align decisions and inspire coherent trade-offs.',
    lifecycleLocation: 'Strategy stage; guides all later work.',
    responsibleRole: 'Product Owner/Product Manager collaboration; PO communicates it for the team.',
    participants: 'Sponsors, team, stakeholders.',
    inputs: 'User needs, business objectives, constraints.',
    outputs: 'Vision statement/board.',
    example: 'Vision: every neighborhood has safe, affordable fresh food within 10 minutes.',
    softwareExample: 'Vision: anyone can send money internationally in under a minute with trust.',
    erpExample: CASE_VISION(),
    relatedTerms: ['product_strategy', 'product_goal'],
    confusedWith: 'Product Goal / Sprint Goal',
    incorrectUsage: 'Vision as a feature laundry list.',
    correctUsage: 'Vision as enduring value direction.',
    category: 'Strategy',
  }),
  term({
    key: 'product_goal', term: 'Product Goal', termAr: 'هدف المنتج',
    simpleMeaning: 'The longer-term objective the Scrum Team plans to achieve for the product.',
    simpleMeaningAr: 'الهدف الأطول أجلاً الذي يخطط فريق سكرم لتحقيقه للمنتج.',
    professionalDefinition: 'A commitment to the Product Backlog describing a future state of the product that can serve as a target for the Scrum Team to plan against.',
    purpose: 'Focus multiple Sprints toward a coherent outcome.',
    lifecycleLocation: 'Product Backlog commitment; strategy-to-delivery bridge.',
    responsibleRole: 'Product Owner.',
    participants: 'Scrum Team; stakeholders informed.',
    inputs: 'Vision, evidence, constraints.',
    outputs: 'A clear Product Goal statement.',
    example: 'Make the cafe the most trusted weekday lunch spot in the district within 6 months.',
    softwareExample: 'Increase activation to 40% for new signups this quarter.',
    erpExample: 'Trusted stock visibility for Warehouse A toward 95% inventory accuracy.',
    relatedTerms: ['product_vision', 'sprint_goal', 'outcome'],
    confusedWith: 'Sprint Goal',
    incorrectUsage: 'Hundreds of simultaneous Product Goals.',
    correctUsage: 'One Product Goal focus at a time for the Product Backlog.',
    category: 'Strategy',
  }),
  term({
    key: 'sprint_goal', term: 'Sprint Goal', termAr: 'هدف السباق',
    simpleMeaning: 'The single main purpose of the current Sprint — why this Sprint matters.',
    simpleMeaningAr: 'الغرض الرئيسي الواحد للسباق الحالي — لماذا يهم هذا السباق.',
    professionalDefinition: 'The single objective for the Sprint; a commitment creating coherence and focus.',
    purpose: 'Protect focus and enable negotiation of scope inside the Sprint.',
    lifecycleLocation: 'Created in Sprint Planning; protected during Sprint.',
    responsibleRole: 'Scrum Team crafts it; PO ensures value purpose.',
    participants: 'Product Owner and Developers.',
    inputs: 'Product Goal, ordered backlog, capacity.',
    outputs: 'Sprint Goal statement + Sprint Backlog.',
    example: 'This week: launch a reliable breakfast combo customers reorder.',
    softwareExample: 'Enable password reset end-to-end for registered users.',
    erpExample: 'Enable accurate goods-receipt posting for Warehouse A locations.',
    relatedTerms: ['product_goal', 'sprint_planning', 'sprint_backlog'],
    confusedWith: 'Product Goal / list of tasks',
    incorrectUsage: 'Sprint Goal = "finish all tickets".',
    correctUsage: 'A coherent value objective that can survive scope negotiation.',
    category: 'Scrum',
  }),
  term({
    key: 'product_backlog', term: 'Product Backlog', termAr: 'قائمة مهام المنتج',
    simpleMeaning: 'The ordered list of everything that might improve the product.',
    simpleMeaningAr: 'القائمة المرتبة لكل ما قد يحسّن المنتج.',
    professionalDefinition: 'An emergent, ordered list of what is needed to improve the product; the single source of work for the Scrum Team.',
    purpose: 'Create transparency and a single ordering authority for value.',
    lifecycleLocation: 'Living artifact across the product lifecycle.',
    responsibleRole: 'Product Owner.',
    participants: 'Scrum Team refines; stakeholders provide input.',
    inputs: 'Ideas, defects, risks, improvements, feedback.',
    outputs: 'Ordered items feeding Sprint Planning.',
    example: 'A restaurant improvement list ordered by customer impact.',
    softwareExample: 'Jira/Azure DevOps product backlog ordered by PO.',
    erpExample: 'Horizon Inventory backlog: receipts, availability, transfers, then scanning.',
    relatedTerms: ['sprint_backlog', 'backlog_item', 'refinement'],
    confusedWith: 'Sprint Backlog / request inbox',
    incorrectUsage: 'Multiple competing backlogs owned by departments.',
    correctUsage: 'One transparent Product Backlog ordered by the PO.',
    category: 'Artifacts',
  }),
  term({
    key: 'sprint_backlog', term: 'Sprint Backlog', termAr: 'قائمة مهام السباق',
    simpleMeaning: 'The plan for the current Sprint: Sprint Goal, selected items, and the team\'s plan to deliver them.',
    simpleMeaningAr: 'خطة السباق الحالي: هدف السباق والعناصر المختارة وخطة الفريق لتسليمها.',
    professionalDefinition: 'Composed of the Sprint Goal, the Product Backlog items selected for the Sprint, and an actionable plan for delivering the Increment.',
    purpose: 'Make the Sprint plan transparent and adaptable by Developers.',
    lifecycleLocation: 'Created in Sprint Planning; updated during Sprint.',
    responsibleRole: 'Developers own the Sprint Backlog plan.',
    participants: 'Developers; PO collaborates on the "what/why".',
    inputs: 'Product Backlog, capacity, Sprint Goal.',
    outputs: 'Visible Sprint plan and evolving tasks.',
    example: 'This week\'s kitchen plan for the lunch special.',
    softwareExample: 'Sprint board with selected stories and tasks.',
    erpExample: 'Selected receiving stories and implementation tasks for the Sprint.',
    relatedTerms: ['product_backlog', 'sprint_goal'],
    confusedWith: 'Product Backlog',
    incorrectUsage: 'Stakeholders adding Sprint Backlog items directly.',
    correctUsage: 'Developers manage Sprint Backlog toward the Sprint Goal.',
    category: 'Artifacts',
  }),
  term({
    key: 'increment', term: 'Increment', termAr: 'الزيادة',
    simpleMeaning: 'A usable piece of product that meets the Definition of Done and adds value.',
    simpleMeaningAr: 'جزء قابل للاستخدام من المنتج يستوفي تعريف الإنجاز ويضيف قيمة.',
    professionalDefinition: 'A concrete stepping stone toward the Product Goal; each Increment is additive and thoroughly verified, meeting the Definition of Done.',
    purpose: 'Create inspectable value frequently.',
    lifecycleLocation: 'Produced every Sprint (and potentially more often).',
    responsibleRole: 'Developers create; PO accepts from a value perspective.',
    participants: 'Scrum Team; stakeholders inspect at Review.',
    inputs: 'Sprint Backlog work.',
    outputs: 'Done usable product state.',
    example: 'A newly opened cafe seating area customers can use now.',
    softwareExample: 'A released feature toggleable in production.',
    erpExample: 'Receiving posting usable in Warehouse A meeting DoD.',
    relatedTerms: ['definition_of_done', 'sprint_review'],
    confusedWith: 'Partial unfinished work',
    incorrectUsage: 'Calling unfinished screens an Increment.',
    correctUsage: 'Only Done work counts as Increment.',
    category: 'Artifacts',
  }),
  term({
    key: 'definition_of_done', term: 'Definition of Done', termAr: 'تعريف الإنجاز',
    simpleMeaning: 'The shared quality checklist that work must meet before it counts as finished.',
    simpleMeaningAr: 'قائمة تحقق الجودة المشتركة التي يجب أن يستوفيها العمل قبل اعتباره منتهياً.',
    professionalDefinition: 'A formal description of the state of the Increment when it meets the quality measures required for the product.',
    purpose: 'Ensure transparency of quality and completeness.',
    lifecycleLocation: 'Applies to every Increment.',
    responsibleRole: 'Scrum Team creates/adheres; organization may define minimums.',
    participants: 'Developers primarily; PO understands implications.',
    inputs: 'Quality standards, compliance needs.',
    outputs: 'Done Increment or not-Done work.',
    example: 'A dish is Done only if cooked, plated, and food-safety checked.',
    softwareExample: 'Code reviewed, tested, integrated, docs updated.',
    erpExample: 'Config/tested/migrated/security roles verified before Done.',
    relatedTerms: ['acceptance_criteria', 'increment'],
    confusedWith: 'Acceptance Criteria',
    incorrectUsage: 'DoD different for every story with no shared standard.',
    correctUsage: 'Shared DoD for quality of the Increment; AC for item-specific behavior.',
    category: 'Quality',
  }),
  term({
    key: 'definition_of_ready', term: 'Definition of Ready', termAr: 'تعريف الجاهزية',
    simpleMeaning: 'A team agreement about when a backlog item is clear enough to be pulled into Sprint Planning.',
    simpleMeaningAr: 'اتفاق الفريق حول متى يكون عنصر قائمة المهام واضحاً بما يكفي لسحبه إلى تخطيط السباق.',
    professionalDefinition: 'A working agreement describing prerequisites for a Product Backlog item to be considered ready for selection in Sprint Planning (not a Scrum mandate, but common practice).',
    purpose: 'Reduce mid-Sprint confusion and thrash.',
    lifecycleLocation: 'Refinement → Sprint Planning gate.',
    responsibleRole: 'Scrum Team agreement; PO ensures items can meet it.',
    participants: 'PO and Developers.',
    inputs: 'Clarified stories, dependencies, AC drafts.',
    outputs: 'Sprint-ready items.',
    example: 'Ingredients measured and recipe understood before cooking shift starts.',
    softwareExample: 'Story has user, value, AC, dependencies known.',
    erpExample: 'Receiving story has business rules, roles, and edge cases clarified.',
    relatedTerms: ['refinement', 'acceptance_criteria'],
    confusedWith: 'Definition of Done',
    incorrectUsage: 'Weaponizing Ready to create waterfall analysis paralysis.',
    correctUsage: 'Lightweight readiness that enables Sprint success.',
    category: 'Quality',
  }),
  term({
    key: 'user_story', term: 'User Story', termAr: 'قصة المستخدم',
    simpleMeaning: 'A short description of something a user needs, written to invite conversation about value.',
    simpleMeaningAr: 'وصف قصير لشيء يحتاجه المستخدم، يُكتب لفتح حوار حول القيمة.',
    professionalDefinition: 'A concise, user-centered expression of desired functionality used to communicate value and stimulate conversation; often in "As a… I want… So that…" form.',
    purpose: 'Keep work connected to user value and conversation.',
    lifecycleLocation: 'Backlog crafting and refinement.',
    responsibleRole: 'PO accountable for backlog items; anyone may contribute drafts.',
    participants: 'PO, Users/BA/UX, Developers.',
    inputs: 'User needs, outcomes, constraints.',
    outputs: 'Backlog item + conversation + AC.',
    example: 'As a parent, I want a lunch reminder so my child is prepared.',
    softwareExample: 'As a rider, I want to share my trip so someone knows I am safe.',
    erpExample: 'As an inventory controller, I want location on-hand visibility so I can trust counts.',
    relatedTerms: ['epic', 'feature', 'acceptance_criteria', 'invest'],
    confusedWith: 'Task / technical chore',
    incorrectUsage: 'As a developer, I want a table… (no user value).',
    correctUsage: 'User + need + value, vertically sliced where possible.',
    category: 'Requirements',
  }),
  term({
    key: 'acceptance_criteria', term: 'Acceptance Criteria', termAr: 'معايير القبول',
    simpleMeaning: 'The specific conditions that must be true for the Product Owner to accept a backlog item.',
    simpleMeaningAr: 'الشروط المحددة التي يجب أن تتحقق حتى يقبل مالك المنتج عنصر قائمة المهام.',
    professionalDefinition: 'Testable conditions that clarify the expected behavior and boundaries of a backlog item from a product acceptance perspective.',
    purpose: 'Reduce ambiguity and enable verification.',
    lifecycleLocation: 'Refinement and development; used at acceptance.',
    responsibleRole: 'PO accountable; crafted with team.',
    participants: 'PO, Developers, QA/users.',
    inputs: 'Story, business rules, examples.',
    outputs: 'Given/When/Then or equivalent checklist.',
    example: 'Lunch order is accepted only if payment succeeds and allergen flags are shown.',
    softwareExample: 'Password reset email sent within 1 minute for valid accounts.',
    erpExample: 'Receipt cannot post with zero quantity; location required.',
    relatedTerms: ['definition_of_done', 'business_rule', 'example_mapping'],
    confusedWith: 'Definition of Done',
    incorrectUsage: 'AC = "works fine".',
    correctUsage: 'Observable, testable conditions including key exceptions.',
    category: 'Requirements',
  }),
  term({
    key: 'epic', term: 'Epic', termAr: 'ملحمة',
    simpleMeaning: 'A large body of work that is too big to deliver at once and must be broken down.',
    simpleMeaningAr: 'عمل كبير جداً على التسليم دفعة واحدة ويجب تفكيكه.',
    professionalDefinition: 'A large product initiative or outcome-oriented body of work that decomposes into features/stories over time.',
    purpose: 'Organize large value themes without false precision.',
    lifecycleLocation: 'Roadmap and backlog hierarchy.',
    responsibleRole: 'Product Owner.',
    participants: 'Team and stakeholders for shaping.',
    inputs: 'Goals, opportunities.',
    outputs: 'Child features/stories.',
    example: 'Transform the cafe into a full breakfast destination.',
    softwareExample: 'Launch multi-currency wallets.',
    erpExample: 'Trusted multi-warehouse inventory visibility.',
    relatedTerms: ['feature', 'user_story', 'capability'],
    confusedWith: 'User Story',
    incorrectUsage: 'Putting an epic directly into a Sprint unchanged.',
    correctUsage: 'Decompose before Sprint selection.',
    category: 'Requirements',
  }),
  term({
    key: 'mvp', term: 'MVP', termAr: 'الحد الأدنى من المنتج القابل للتطبيق',
    simpleMeaning: 'The smallest version that can test a key value hypothesis with real users.',
    simpleMeaningAr: 'أصغر نسخة يمكنها اختبار فرضية قيمة أساسية مع مستخدمين حقيقيين.',
    professionalDefinition: 'A version of a product that allows a team to collect the maximum validated learning about customers with the least effort.',
    purpose: 'Learn fast with minimal waste.',
    lifecycleLocation: 'Early delivery / discovery validation.',
    responsibleRole: 'PO shapes MVP scope against learning goals.',
    participants: 'Team, users, sponsors.',
    inputs: 'Hypotheses, risks.',
    outputs: 'Learning and next backlog decisions.',
    example: 'Sell pre-orders before building a full bakery storefront.',
    softwareExample: 'Manual concierge behind a signup page before full automation.',
    erpExample: 'Receiving + on-hand visibility for one warehouse before company-wide scanning.',
    relatedTerms: ['mmp', 'hypothesis', 'product_discovery'],
    confusedWith: 'MMP / half-broken release',
    incorrectUsage: 'MVP as excuse for poor quality that users cannot use.',
    correctUsage: 'Smallest safe-to-learn Increment aligned to a hypothesis.',
    category: 'Strategy',
  }),
  term({
    key: 'outcome', term: 'Outcome', termAr: 'النتيجة',
    simpleMeaning: 'A meaningful change in user or business behavior/results — not just that work was delivered.',
    simpleMeaningAr: 'تغيير ذو معنى في سلوك أو نتائج المستخدم أو العمل — ليس فقط أن العمل سُلّم.',
    professionalDefinition: 'A measurable or observable change in customer, user, or organizational results produced by the product.',
    purpose: 'Keep teams focused on value realization.',
    lifecycleLocation: 'Goals, metrics, reviews.',
    responsibleRole: 'PO accountable for pursuing outcomes.',
    participants: 'Stakeholders, users, team.',
    inputs: 'Baseline metrics, hypotheses.',
    outputs: 'Validated learning / metric movement.',
    example: 'Fewer customers leaving because of wait time.',
    softwareExample: 'Activation rate increased.',
    erpExample: 'Inventory accuracy rose from 78% toward 95%.',
    relatedTerms: ['output', 'kpi', 'okr'],
    confusedWith: 'Output',
    incorrectUsage: 'Calling story points an outcome.',
    correctUsage: 'Tie backlog items to outcome hypotheses.',
    category: 'Metrics',
  }),
  term({
    key: 'output', term: 'Output', termAr: 'المُخرَج',
    simpleMeaning: 'What was produced (features, documents, releases) — activity results.',
    simpleMeaningAr: 'ما تم إنتاجه (ميزات، وثائق، إصدارات) — نتائج النشاط.',
    professionalDefinition: 'The artifacts or deliverables produced by the team, independent of whether they created beneficial change.',
    purpose: 'Track delivery activity (secondary to outcomes).',
    lifecycleLocation: 'Delivery reporting.',
    responsibleRole: 'Team produces outputs; PO judges value.',
    participants: 'Scrum Team.',
    inputs: 'Sprint work.',
    outputs: 'Features, reports, releases.',
    example: 'Printed 500 menus (output) vs more returning customers (outcome).',
    softwareExample: 'Shipped 12 features.',
    erpExample: 'Deployed three screens.',
    relatedTerms: ['outcome', 'increment'],
    confusedWith: 'Outcome',
    incorrectUsage: 'Celebrating outputs while outcomes stagnate.',
    correctUsage: 'Report outputs as means; manage to outcomes.',
    category: 'Metrics',
  }),
];

function CASE_VISION(): string {
  return 'Help Meridian teams always know what stock they have, where it is, and what they can promise — without spreadsheets or tribal knowledge.';
}

export function searchTerms(query: string): Term[] {
  const q = query.trim().toLowerCase();
  if (!q) return TERMINOLOGY;
  return TERMINOLOGY.filter((t) =>
    [t.term, t.termAr, t.simpleMeaning, t.professionalDefinition, t.category, ...t.relatedTerms]
      .join(' ')
      .toLowerCase()
      .includes(q),
  );
}

export function getTerm(key: string): Term | undefined {
  return TERMINOLOGY.find((t) => t.key === key);
}
